In [1]:
import pandas as pd

In [2]:
languages_md_county_df = pd.read_csv("raw-county-lang-ACSST5Y2024.S1601-Data.csv")

In [3]:
languages_md_county_df

,GEO_ID,NAME,S1601_C01_001E,S1601_C01_001M,S1601_C01_002E,S1601_C01_002M,S1601_C01_003E,S1601_C01_003M,S1601_C01_004E,S1601_C01_004M,...,S1601_C06_020M,S1601_C06_021E,S1601_C06_021M,S1601_C06_022E,S1601_C06_022M,S1601_C06_023E,S1601_C06_023M,S1601_C06_024E,S1601_C06_024M,Unnamed: 290
0,Geography,Geographic Area Name,Estimate!!Total!!Population 5 years and over,Margin of Error!!Total!!Population 5 years and...,Estimate!!Total!!Population 5 years and over!!...,Margin of Error!!Total!!Population 5 years and...,Estimate!!Total!!Population 5 years and over!!...,Margin of Error!!Total!!Population 5 years and...,Estimate!!Total!!Population 5 years and over!!...,Margin of Error!!Total!!Population 5 years and...,...,Margin of Error!!Percent speak English less th...,Estimate!!Percent speak English less than very...,Margin of Error!!Percent speak English less th...,Estimate!!Percent speak English less than very...,Margin of Error!!Percent speak English less th...,Estimate!!Percent speak English less than very...,Margin of Error!!Percent speak English less th...,Estimate!!Percent speak English less than very...,Margin of Error!!Percent speak English less th...,NaN
1,0500000US24001,"Allegany County, Maryland",64359,74,62313,267,2046,264,891,171,...,0.2,(X),(X),20.7,6.8,25.9,11.0,15.9,9.7,NaN
2,0500000US24003,"Anne Arundel County, Maryland",562765,32,484691,3035,78074,3032,38666,2039,...,0.2,(X),(X),23.8,2.2,23.1,3.6,24.3,2.2,NaN
3,0500000US24005,"Baltimore County, Maryland",802068,17,675495,3459,126573,3458,39803,1890,...,0.2,(X),(X),30.6,1.7,30.4,3.9,30.7,1.9,NaN
4,0500000US24009,"Calvert County, Maryland",89294,13,84061,679,5233,678,2400,484,...,0.4,(X),(X),23.3,6.9,24.3,11.7,22.4,7.2,NaN
5,0500000US24011,"Caroline County, Maryland",31509,27,28823,263,2686,262,2221,179,...,0.4,(X),(X),24.3,10.0,29.6,13.0,8.8,14.9,NaN
6,0500000US24013,"Carroll County, Maryland",165791,*****,154367,1048,11424,1048,4850,537,...,0.2,(X),(X),18.7,3.8,17.2,5.0,19.5,4.7,NaN
7,0500000US24015,"Cecil County, Maryland",99061,33,92183,848,6878,843,3260,475,...,0.5,(X),(X),31.2,7.6,30.1,11.4,32.3,10.8,NaN
8,0500000US24017,"Charles County, Maryland",160722,61,144298,1268,16424,1257,7397,838,...,0.3,(X),(X),19.0,3.4,19.3,5.0,18.8,4.2,NaN
9,0500000US24019,"Dorchester County, Maryland",30925,65,29031,357,1894,331,1323,281,...,0.6,(X),(X),37.1,13.7,37.7,16.3,35.5,24.5,NaN
10,0500000US24021,"Frederick County, Maryland",270156,33,222458,1714,47698,1717,24234,1149,...,0.3,(X),(X),23.3,2.3,25.1,3.3,21.8,3.3,NaN
11,0500000US24023,"Garrett County, Maryland",27277,52,26384,276,893,269,221,86,...,0.1,(X),(X),8.0,6.0,22.0,16.9,4.1,5.3,NaN
12,0500000US24025,"Harford County, Maryland",249534,18,228028,1416,21506,1418,8455,895,...,0.3,(X),(X),24.9,3.1,30.9,7.1,21.5,3.2,NaN
13,0500000US24027,"Howard County, Maryland",318370,50,228314,2529,90056,2526,19654,1032,...,0.4,(X),(X),27.0,1.5,27.4,3.4,26.9,1.7,NaN
14,0500000US24029,"Kent County, Maryland",18547,172,17611,313,936,265,597,201,...,0.6,(X),(X),20.9,12.9,22.3,20.7,18.8,11.9,NaN
15,0500000US24031,"Montgomery County, Maryland",1004869,28,573273,4557,431596,4556,177910,2359,...,0.4,(X),(X),31.1,1.0,33.7,1.5,29.7,1.2,NaN
16,0500000US24033,"Prince George's County, Maryland",901354,15,624348,4565,277006,4567,175654,2078,...,0.2,(X),(X),31.0,1.3,38.5,1.9,24.4,1.6,NaN
17,0500000US24035,"Queen Anne's County, Maryland",49094,56,46278,389,2816,387,1822,244,...,0.2,(X),(X),14.6,6.6,14.6,9.9,14.6,8.5,NaN
18,0500000US24037,"St. Mary's County, Maryland",108101,52,100166,1122,7935,1125,2635,579,...,0.4,(X),(X),25.7,6.1,28.9,11.6,23.5,6.1,NaN
19,0500000US24039,"Somerset County, Maryland",23669,74,22140,618,1529,607,622,171,...,0.4,(X),(X),16.8,9.6,18.3,14.1,15.4,13.5,NaN
20,0500000US24041,"Talbot County, Maryland",36261,138,32658,445,3603,448,2559,383,...,0.5,(X),(X),24.9,8.5,19.6,10.1,31.7,14.2,NaN
21,0500000US24043,"Washington County, Maryland",147184,26,133408,1186,13776,1185,8209,848,...,0.3,(X),(X),21.6,4.6,28.8,7.1,13.6,4.1,NaN
22,0500000US24045,"Wicomico County, Maryland",98582,69,84858,1343,13724,1358,5443,573,...,0.6,(X),(X),31.5,5.2,22.0,7.0,37.9,7.4,NaN
23,0500000US24047,"Worcester County, Maryland",51499,96,48248,481,3251,451,1251,289,...,0.2,(X),(X),10.8,6.3,4.5,4.9,13.2,7.9,NaN
24,0500000US24510,"Baltimore city, Maryland",538642,51,474192,2466,64450,2464,31973,1621,...,0.2,(X),(X),28.2,2.1,30.5,3.6,26.5,2.6,NaN

In [4]:
languages_md_county_df.columns = languages_md_county_df.iloc[0]

In [5]:
languages_md_county_df.drop(0, inplace = True)

In [6]:
languages_md_county_df.reset_index(drop = True)

,Geography,Geographic Area Name,Estimate!!Total!!Population 5 years and over,Margin of Error!!Total!!Population 5 years and over,Estimate!!Total!!Population 5 years and over!!Speak only English,Margin of Error!!Total!!Population 5 years and over!!Speak only English,Estimate!!Total!!Population 5 years and over!!Speak a language other than English,Margin of Error!!Total!!Population 5 years and over!!Speak a language other than English,Estimate!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish,Margin of Error!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish,...,"Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over""","Estimate!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak only English""","Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak only English""","Estimate!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English""","Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English""","Estimate!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English!!Spanish""","Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English!!Spanish""","Estimate!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English!!Other languages""","Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English!!Other languages""",NaN
0,0500000US24001,"Allegany County, Maryland",64359,74,62313,267,2046,264,891,171,...,0.2,(X),(X),20.7,6.8,25.9,11.0,15.9,9.7,NaN
1,0500000US24003,"Anne Arundel County, Maryland",562765,32,484691,3035,78074,3032,38666,2039,...,0.2,(X),(X),23.8,2.2,23.1,3.6,24.3,2.2,NaN
2,0500000US24005,"Baltimore County, Maryland",802068,17,675495,3459,126573,3458,39803,1890,...,0.2,(X),(X),30.6,1.7,30.4,3.9,30.7,1.9,NaN
3,0500000US24009,"Calvert County, Maryland",89294,13,84061,679,5233,678,2400,484,...,0.4,(X),(X),23.3,6.9,24.3,11.7,22.4,7.2,NaN
4,0500000US24011,"Caroline County, Maryland",31509,27,28823,263,2686,262,2221,179,...,0.4,(X),(X),24.3,10.0,29.6,13.0,8.8,14.9,NaN
5,0500000US24013,"Carroll County, Maryland",165791,*****,154367,1048,11424,1048,4850,537,...,0.2,(X),(X),18.7,3.8,17.2,5.0,19.5,4.7,NaN
6,0500000US24015,"Cecil County, Maryland",99061,33,92183,848,6878,843,3260,475,...,0.5,(X),(X),31.2,7.6,30.1,11.4,32.3,10.8,NaN
7,0500000US24017,"Charles County, Maryland",160722,61,144298,1268,16424,1257,7397,838,...,0.3,(X),(X),19.0,3.4,19.3,5.0,18.8,4.2,NaN
8,0500000US24019,"Dorchester County, Maryland",30925,65,29031,357,1894,331,1323,281,...,0.6,(X),(X),37.1,13.7,37.7,16.3,35.5,24.5,NaN
9,0500000US24021,"Frederick County, Maryland",270156,33,222458,1714,47698,1717,24234,1149,...,0.3,(X),(X),23.3,2.3,25.1,3.3,21.8,3.3,NaN
10,0500000US24023,"Garrett County, Maryland",27277,52,26384,276,893,269,221,86,...,0.1,(X),(X),8.0,6.0,22.0,16.9,4.1,5.3,NaN
11,0500000US24025,"Harford County, Maryland",249534,18,228028,1416,21506,1418,8455,895,...,0.3,(X),(X),24.9,3.1,30.9,7.1,21.5,3.2,NaN
12,0500000US24027,"Howard County, Maryland",318370,50,228314,2529,90056,2526,19654,1032,...,0.4,(X),(X),27.0,1.5,27.4,3.4,26.9,1.7,NaN
13,0500000US24029,"Kent County, Maryland",18547,172,17611,313,936,265,597,201,...,0.6,(X),(X),20.9,12.9,22.3,20.7,18.8,11.9,NaN
14,0500000US24031,"Montgomery County, Maryland",1004869,28,573273,4557,431596,4556,177910,2359,...,0.4,(X),(X),31.1,1.0,33.7,1.5,29.7,1.2,NaN
15,0500000US24033,"Prince George's County, Maryland",901354,15,624348,4565,277006,4567,175654,2078,...,0.2,(X),(X),31.0,1.3,38.5,1.9,24.4,1.6,NaN
16,0500000US24035,"Queen Anne's County, Maryland",49094,56,46278,389,2816,387,1822,244,...,0.2,(X),(X),14.6,6.6,14.6,9.9,14.6,8.5,NaN
17,0500000US24037,"St. Mary's County, Maryland",108101,52,100166,1122,7935,1125,2635,579,...,0.4,(X),(X),25.7,6.1,28.9,11.6,23.5,6.1,NaN
18,0500000US24039,"Somerset County, Maryland",23669,74,22140,618,1529,607,622,171,...,0.4,(X),(X),16.8,9.6,18.3,14.1,15.4,13.5,NaN
19,0500000US24041,"Talbot County, Maryland",36261,138,32658,445,3603,448,2559,383,...,0.5,(X),(X),24.9,8.5,19.6,10.1,31.7,14.2,NaN
20,0500000US24043,"Washington County, Maryland",147184,26,133408,1186,13776,1185,8209,848,...,0.3,(X),(X),21.6,4.6,28.8,7.1,13.6,4.1,NaN
21,0500000US24045,"Wicomico County, Maryland",98582,69,84858,1343,13724,1358,5443,573,...,0.6,(X),(X),31.5,5.2,22.0,7.0,37.9,7.4,NaN
22,0500000US24047,"Worcester County, Maryland",51499,96,48248,481,3251,451,1251,289,...,0.2,(X),(X),10.8,6.3,4.5,4.9,13.2,7.9,NaN
23,0500000US24510,"Baltimore city, Maryland",538642,51,474192,2466,64450,2464,31973,1621,...,0.2,(X),(X),28.2,2.1,30.5,3.6,26.5,2.6,NaN

In [7]:
languages_md_county_df.drop('Geography', axis=1)

,Geographic Area Name,Estimate!!Total!!Population 5 years and over,Margin of Error!!Total!!Population 5 years and over,Estimate!!Total!!Population 5 years and over!!Speak only English,Margin of Error!!Total!!Population 5 years and over!!Speak only English,Estimate!!Total!!Population 5 years and over!!Speak a language other than English,Margin of Error!!Total!!Population 5 years and over!!Speak a language other than English,Estimate!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish,Margin of Error!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish,Estimate!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish!!5 to 17 years old,...,"Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over""","Estimate!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak only English""","Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak only English""","Estimate!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English""","Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English""","Estimate!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English!!Spanish""","Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English!!Spanish""","Estimate!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English!!Other languages""","Margin of Error!!Percent speak English less than very well""!!Percent of specified language speakers!!CITIZENS 18 YEARS AND OVER!!All citizens 18 years old and over!!Speak a language other than English!!Other languages""",NaN
1,"Allegany County, Maryland",64359,74,62313,267,2046,264,891,171,46,...,0.2,(X),(X),20.7,6.8,25.9,11.0,15.9,9.7,NaN
2,"Anne Arundel County, Maryland",562765,32,484691,3035,78074,3032,38666,2039,8356,...,0.2,(X),(X),23.8,2.2,23.1,3.6,24.3,2.2,NaN
3,"Baltimore County, Maryland",802068,17,675495,3459,126573,3458,39803,1890,10662,...,0.2,(X),(X),30.6,1.7,30.4,3.9,30.7,1.9,NaN
4,"Calvert County, Maryland",89294,13,84061,679,5233,678,2400,484,323,...,0.4,(X),(X),23.3,6.9,24.3,11.7,22.4,7.2,NaN
5,"Caroline County, Maryland",31509,27,28823,263,2686,262,2221,179,675,...,0.4,(X),(X),24.3,10.0,29.6,13.0,8.8,14.9,NaN
6,"Carroll County, Maryland",165791,*****,154367,1048,11424,1048,4850,537,842,...,0.2,(X),(X),18.7,3.8,17.2,5.0,19.5,4.7,NaN
7,"Cecil County, Maryland",99061,33,92183,848,6878,843,3260,475,615,...,0.5,(X),(X),31.2,7.6,30.1,11.4,32.3,10.8,NaN
8,"Charles County, Maryland",160722,61,144298,1268,16424,1257,7397,838,1361,...,0.3,(X),(X),19.0,3.4,19.3,5.0,18.8,4.2,NaN
9,"Dorchester County, Maryland",30925,65,29031,357,1894,331,1323,281,325,...,0.6,(X),(X),37.1,13.7,37.7,16.3,35.5,24.5,NaN
10,"Frederick County, Maryland",270156,33,222458,1714,47698,1717,24234,1149,5052,...,0.3,(X),(X),23.3,2.3,25.1,3.3,21.8,3.3,NaN
11,"Garrett County, Maryland",27277,52,26384,276,893,269,221,86,17,...,0.1,(X),(X),8.0,6.0,22.0,16.9,4.1,5.3,NaN
12,"Harford County, Maryland",249534,18,228028,1416,21506,1418,8455,895,1466,...,0.3,(X),(X),24.9,3.1,30.9,7.1,21.5,3.2,NaN
13,"Howard County, Maryland",318370,50,228314,2529,90056,2526,19654,1032,4214,...,0.4,(X),(X),27.0,1.5,27.4,3.4,26.9,1.7,NaN
14,"Kent County, Maryland",18547,172,17611,313,936,265,597,201,89,...,0.6,(X),(X),20.9,12.9,22.3,20.7,18.8,11.9,NaN
15,"Montgomery County, Maryland",1004869,28,573273,4557,431596,4556,177910,2359,38831,...,0.4,(X),(X),31.1,1.0,33.7,1.5,29.7,1.2,NaN
16,"Prince George's County, Maryland",901354,15,624348,4565,277006,4567,175654,2078,45752,...,0.2,(X),(X),31.0,1.3,38.5,1.9,24.4,1.6,NaN
17,"Queen Anne's County, Maryland",49094,56,46278,389,2816,387,1822,244,595,...,0.2,(X),(X),14.6,6.6,14.6,9.9,14.6,8.5,NaN
18,"St. Mary's County, Maryland",108101,52,100166,1122,7935,1125,2635,579,289,...,0.4,(X),(X),25.7,6.1,28.9,11.6,23.5,6.1,NaN
19,"Somerset County, Maryland",23669,74,22140,618,1529,607,622,171,102,...,0.4,(X),(X),16.8,9.6,18.3,14.1,15.4,13.5,NaN
20,"Talbot County, Maryland",36261,138,32658,445,3603,448,2559,383,763,...,0.5,(X),(X),24.9,8.5,19.6,10.1,31.7,14.2,NaN
21,"Washington County, Maryland",147184,26,133408,1186,13776,1185,8209,848,1725,...,0.3,(X),(X),21.6,4.6,28.8,7.1,13.6,4.1,NaN
22,"Wicomico County, Maryland",98582,69,84858,1343,13724,1358,5443,573,1595,...,0.6,(X),(X),31.5,5.2,22.0,7.0,37.9,7.4,NaN
23,"Worcester County, Maryland",51499,96,48248,481,3251,451,1251,289,262,...,0.2,(X),(X),10.8,6.3,4.5,4.9,13.2,7.9,NaN
24,"Baltimore city, Maryland",538642,51,474192,2466,64450,2464,31973,1621,8363,...,0.2,(X),(X),28.2,2.1,30.5,3.6,26.5,2.6,NaN

In [8]:
languages_md_county_df=languages_md_county_df.dropna(axis=1)

In [9]:
languages_md_county_df_long = languages_md_county_df.copy()

In [10]:
#rename columns
languages_md_county_df_long.rename(columns={
    
     'Estimate!!Percent!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish!!65 years old and over': 'spanish_pct_65_plus',
    'Margin of Error!!Percent!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish!!65 years old and over': 'moe_spanish_pct_65_plus',
     'Estimate!!Percent!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other Indo-European languages!!65 years old and over': 'indo_euro_pct_65_plus',
    'Margin of Error!!Percent!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other Indo-European languages!!65 years old and over': 'moe_indo_euro_pct_65_plus',
     'Estimate!!Percent!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Asian and Pacific Island languages!!65 years old and over': 'asian_pacific_pct_65_plus',
    'Margin of Error!!Percent!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Asian and Pacific Island languages!!65 years old and over': 'moe_asian_pacific_pct_65_plus',
     'Estimate!!Percent!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other languages!!65 years old and over': 'other_lang_pct_65_plus',
    'Margin of Error!!Percent!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other languages!!65 years old and over': 'moe_other_lang_pct_65_plus',


    'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over"':'lep_pct_over_5',
     'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over"':'moe_lep_pct_over_5',
     'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish"':'lep_pct_spanish',
     'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish"':'moe_lep_pct_spanish',
     'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish!!65 years old and over"':'lep_pct_spanish_65_plus',
     'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish!!65 years old and over"':'moe_lep_pct_spanish_65_plus',
     'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other Indo-European languages"':'lep_pct_indo_euro',
     'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other Indo-European languages"':'moe_lep_pct_indo_euro',
     'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other Indo-European languages!!65 years old and over"':'lep_pct_indo_euro_65_plus',
     'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other Indo-European languages!!65 years old and over"':'moe_lep_pct_indo_euro_65_plus',
     'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Asian and Pacific Island languages"':'lep_pct_asian_pacific',
     'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Asian and Pacific Island languages"':'moe_lep_pct_asian_pacific',
     'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Asian and Pacific Island languages!!65 years old and over"': 'lep_pct_asian_pacific_65_plus',
     'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Asian and Pacific Island languages!!65 years old and over"': 'moe_lep_pct_asian_pacific_65_plus',
     'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other languages"':'lep_pct_other',
     'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other languages"': 'moe_lep_pct_other',
     'Estimate!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other languages!!65 years old and over"':'lep_pct_other_65_plus',
    'Margin of Error!!Percent speak English less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other languages!!65 years old and over"':'moe_lep_pct_other_65_plus'}, inplace=True)

In [11]:
#language by percentage
languages_pct_df_long = languages_md_county_df_long.melt(
    id_vars = ['Geography', 'Geographic Area Name'],
    value_vars = ['spanish_pct_65_plus',
                  
                  'indo_euro_pct_65_plus',
                  
                  'asian_pacific_pct_65_plus',
                
                  'othamer_lang_pct_65_plus'],
    var_name = 'language',
    value_name = 'pct_65_plus')
    
#language spoken at home among LEP by percentage
languages_lep_pct_df_long = languages_md_county_df_long.melt(
    id_vars = ['Geography', 'Geographic Area Name'],
    value_vars = ['lep_pct_over_5',
                
                  'lep_pct_spanish', 
            
                  'lep_pct_spanish_65_plus',
                 
                  'lep_pct_indo_euro',
                
                  'lep_pct_indo_euro_65_plus',
                 
                  'lep_pct_asian_pacific',
              
                  'lep_pct_asian_pacific_65_plus',
                  
                  'lep_pct_other',
              
                  'lep_pct_other_65_plus'],
    var_name = 'language',
    value_name = 'lep_pct')

In [12]:
#MOE language by percentage
moe_languages_pct_df_long = languages_md_county_df_long.melt(
    id_vars = ['Geography', 'Geographic Area Name'],
    value_vars = [
                  'moe_spanish_pct_65_plus',
                  
                  'moe_indo_euro_pct_65_plus',
                  
                  'moe_asian_pacific_pct_65_plus',
                  
                 'moe_other_lang_pct_65_plus'],
    var_name = 'language',
    value_name = 'moe_pct_65_plus')

    
#MOE language spoken at home among LEP by percentage
moe_languages_lep_pct_df_long = languages_md_county_df_long.melt(
    id_vars = ['Geography', 'Geographic Area Name'],
    value_vars = [
                  'moe_lep_pct_over_5',
                  
                  'moe_lep_pct_spanish',
       
                  'moe_lep_pct_spanish_65_plus',
            
                  'moe_lep_pct_indo_euro',
                
                  'moe_lep_pct_indo_euro_65_plus',
              
                  'moe_lep_pct_asian_pacific',
               
                  'moe_lep_pct_asian_pacific_65_plus',
          
                  'moe_lep_pct_other',
              
                  'moe_lep_pct_other_65_plus'],
    var_name = 'language',
    value_name = 'moe_lep_pct_65_plus')

In [13]:
moe_languages_pct_df_long['language'] = moe_languages_pct_df_long['language'].str.replace('moe_','')
moe_languages_lep_pct_df_long['language'] = moe_languages_lep_pct_df_long['language'].str.replace('moe_','')

In [14]:
languages_pct_moe_df_long = pd.merge(languages_pct_df_long, moe_languages_pct_df_long,
                                       on=['Geography', 'Geographic Area Name', 'language'], 
                                       how='inner')

languages_lep_pct_moe_df_long = pd.merge(languages_lep_pct_df_long, moe_languages_lep_pct_df_long,
                                       on=['Geography', 'Geographic Area Name', 'language'], 
                                       how='inner')

In [15]:
pd.set_option('display.max_rows', None)
languages_pct_moe_df_long

,Geography,Geographic Area Name,language,pct_65_plus,moe_pct_65_plus
0,0500000US24001,"Allegany County, Maryland",spanish_pct_65_plus,0.3,0.1
1,0500000US24003,"Anne Arundel County, Maryland",spanish_pct_65_plus,0.4,0.1
2,0500000US24005,"Baltimore County, Maryland",spanish_pct_65_plus,0.3,0.1
3,0500000US24009,"Calvert County, Maryland",spanish_pct_65_plus,0.1,0.1
4,0500000US24011,"Caroline County, Maryland",spanish_pct_65_plus,0.4,0.2
5,0500000US24013,"Carroll County, Maryland",spanish_pct_65_plus,0.2,0.1
6,0500000US24015,"Cecil County, Maryland",spanish_pct_65_plus,0.3,0.1
7,0500000US24017,"Charles County, Maryland",spanish_pct_65_plus,0.3,0.1
8,0500000US24019,"Dorchester County, Maryland",spanish_pct_65_plus,0.3,0.2
9,0500000US24021,"Frederick County, Maryland",spanish_pct_65_plus,0.6,0.1
10,0500000US24023,"Garrett County, Maryland",spanish_pct_65_plus,0.1,0.1
11,0500000US24025,"Harford County, Maryland",spanish_pct_65_plus,0.3,0.1
12,0500000US24027,"Howard County, Maryland",spanish_pct_65_plus,0.5,0.1
13,0500000US24029,"Kent County, Maryland",spanish_pct_65_plus,0.2,0.1
14,0500000US24031,"Montgomery County, Maryland",spanish_pct_65_plus,1.7,0.1
15,0500000US24033,"Prince George's County, Maryland",spanish_pct_65_plus,1.1,0.1
16,0500000US24035,"Queen Anne's County, Maryland",spanish_pct_65_plus,0.2,0.1
17,0500000US24037,"St. Mary's County, Maryland",spanish_pct_65_plus,0.2,0.1
18,0500000US24039,"Somerset County, Maryland",spanish_pct_65_plus,0.2,0.2
19,0500000US24041,"Talbot County, Maryland",spanish_pct_65_plus,0.4,0.2
20,0500000US24043,"Washington County, Maryland",spanish_pct_65_plus,0.4,0.1
21,0500000US24045,"Wicomico County, Maryland",spanish_pct_65_plus,0.5,0.3
22,0500000US24047,"Worcester County, Maryland",spanish_pct_65_plus,0.3,0.2
23,0500000US24510,"Baltimore city, Maryland",spanish_pct_65_plus,0.4,0.1
24,0500000US24001,"Allegany County, Maryland",indo_euro_pct_65_plus,0.2,0.1
25,0500000US24003,"Anne Arundel County, Maryland",indo_euro_pct_65_plus,0.5,0.1
26,0500000US24005,"Baltimore County, Maryland",indo_euro_pct_65_plus,0.9,0.1
27,0500000US24009,"Calvert County, Maryland",indo_euro_pct_65_plus,0.3,0.1
28,0500000US24011,"Caroline County, Maryland",indo_euro_pct_65_plus,0.2,0.1
29,0500000US24013,"Carroll County, Maryland",indo_euro_pct_65_plus,0.4,0.1
30,0500000US24015,"Cecil County, Maryland",indo_euro_pct_65_plus,0.3,0.1
31,0500000US24017,"Charles County, Maryland",indo_euro_pct_65_plus,0.3,0.1
32,0500000US24019,"Dorchester County, Maryland",indo_euro_pct_65_plus,0.6,0.5
33,0500000US24021,"Frederick County, Maryland",indo_euro_pct_65_plus,0.5,0.1
34,0500000US24023,"Garrett County, Maryland",indo_euro_pct_65_plus,0.5,0.3
35,0500000US24025,"Harford County, Maryland",indo_euro_pct_65_plus,0.7,0.2
36,0500000US24027,"Howard County, Maryland",indo_euro_pct_65_plus,1.1,0.2
37,0500000US24029,"Kent County, Maryland",indo_euro_pct_65_plus,0.1,0.1
38,0500000US24031,"Montgomery County, Maryland",indo_euro_pct_65_plus,1.8,0.1
39,0500000US24033,"Prince George's County, Maryland",indo_euro_pct_65_plus,0.5,0.1
40,0500000US24035,"Queen Anne's County, Maryland",indo_euro_pct_65_plus,0.4,0.2
41,0500000US24037,"St. Mary's County, Maryland",indo_euro_pct_65_plus,0.2,0.1
42,0500000US24039,"Somerset County, Maryland",indo_euro_pct_65_plus,0.1,0.1
43,0500000US24041,"Talbot County, Maryland",indo_euro_pct_65_plus,0.8,0.4
44,0500000US24043,"Washington County, Maryland",indo_euro_pct_65_plus,0.3,0.1
45,0500000US24045,"Wicomico County, Maryland",indo_euro_pct_65_plus,0.5,0.2
46,0500000US24047,"Worcester County, Maryland",indo_euro_pct_65_plus,0.8,0.4
47,0500000US24510,"Baltimore city, Maryland",indo_euro_pct_65_plus,0.4,0.1
48,0500000US24001,"Allegany County, Maryland",asian_pacific_pct_65_plus,0.0,0.1
49,0500000US24003,"Anne Arundel County, Maryland",asian_pacific_pct_65_plus,0.5,0.1
50,0500000US24005,"Baltimore County, Maryland",asian_pacific_pct_65_plus,0.5,0.1
51,0500000US24009,"Calvert County, Maryland",asian_pacific_pct_65_plus,0.3,0.1
52,0500000US24011,"Caroline County, Maryland",asian_pacific_pct_65_plus,0.0,0.1
53,0500000US24013,"Carroll County, Maryland",asian_pacific_pct_65_plus,0.2,0.1
54,0500000US24015,"Cecil County, Maryland",asian_pacific_pct_65_plus,0.1,0.1
55,0500000US24017,"Charles County, Maryland",asian_pacific_pct_65_plus,0.3,0.1
56,0500000US24019,"Dorchester County, Maryland",asian_pacific_pct_65_plus,0.3,0.2
57,0500000US24021,"Frederick County, Maryland",asian_pacific_pct_65_plus,0.4,0.1
58,0500000US24023,"Garrett County, Maryland",asian_pacific_pct_65_plus,0.0,0.1
59,0500000US24025,"Harford County, Maryland",asian_pacific_pct_65_plus,0.3,0.1
60,0500000US24027,"Howard County, Maryland",asian_pacific_pct_65_plus,1.7,0.2
61,0500000US24029,"Kent County, Maryland",asian_pacific_pct_65_plus,0.0,0.2
62,0500000US24031,"Montgomery County, Maryland",asian_pacific_pct_65_plus,2.1,0.1
63,0500000US24033,"Prince George's County, Maryland",asian_pacific_pct_65_plus,0.5,0.1
64,0500000US24035,"Queen Anne's County, Maryland",asian_pacific_pct_65_plus,0.2,0.1
65,0500000US24037,"St. Mary's County, Maryland",asian_pacific_pct_65_plus,0.3,0.1
66,0500000US24039,"Somerset County, Maryland",asian_pacific_pct_65_plus,0.0,0.2
67,0500000US24041,"Talbot County, Maryland",asian_pacific_pct_65_plus,0.2,0.1
68,0500000US24043,"Washington County, Maryland",asian_pacific_pct_65_plus,0.2,0.1
69,0500000US24045,"Wicomico County, Maryland",asian_pacific_pct_65_plus,0.2,0.2
70,0500000US24047,"Worcester County, Maryland",asian_pacific_pct_65_plus,0.0,0.1
71,0500000US24510,"Baltimore city, Maryland",asian_pacific_pct_65_plus,0.2,0.1
72,0500000US24001,"Allegany County, Maryland",other_lang_pct_65_plus,0.0,0.1
73,0500000US24003,"Anne Arundel County, Maryland",other_lang_pct_65_plus,0.1,0.1
74,0500000US24005,"Baltimore County, Maryland",other_lang_pct_65_plus,0.3,0.1
75,0500000US24009,"Calvert County, Maryland",other_lang_pct_65_plus,0.0,0.1
76,0500000US24011,"Caroline County, Maryland",other_lang_pct_65_plus,0.0,0.1
77,0500000US24013,"Carroll County, Maryland",other_lang_pct_65_plus,0.0,0.1
78,0500000US24015,"Cecil County, Maryland",other_lang_pct_65_plus,0.0,0.1
79,0500000US24017,"Charles County, Maryland",other_lang_pct_65_plus,0.1,0.1
80,0500000US24019,"Dorchester County, Maryland",other_lang_pct_65_plus,0.0,0.1
81,0500000US24021,"Frederick County, Maryland",other_lang_pct_65_plus,0.2,0.1
82,0500000US24023,"Garrett County, Maryland",other_lang_pct_65_plus,0.0,0.2
83,0500000US24025,"Harford County, Maryland",other_lang_pct_65_plus,0.1,0.1
84,0500000US24027,"Howard County, Maryland",other_lang_pct_65_plus,0.2,0.1
85,0500000US24029,"Kent County, Maryland",other_lang_pct_65_plus,0.0,0.2
86,0500000US24031,"Montgomery County, Maryland",other_lang_pct_65_plus,0.6,0.1
87,0500000US24033,"Prince George's County, Maryland",other_lang_pct_65_plus,0.6,0.1
88,0500000US24035,"Queen Anne's County, Maryland",other_lang_pct_65_plus,0.0,0.1
89,0500000US24037,"St. Mary's County, Maryland",other_lang_pct_65_plus,0.0,0.1
90,0500000US24039,"Somerset County, Maryland",other_lang_pct_65_plus,0.2,0.3
91,0500000US24041,"Talbot County, Maryland",other_lang_pct_65_plus,0.0,0.1
92,0500000US24043,"Washington County, Maryland",other_lang_pct_65_plus,0.1,0.1
93,0500000US24045,"Wicomico County, Maryland",other_lang_pct_65_plus,0.0,0.1
94,0500000US24047,"Worcester County, Maryland",other_lang_pct_65_plus,0.0,0.1
95,0500000US24510,"Baltimore city, Maryland",other_lang_pct_65_plus,0.1,0.1

In [16]:
languages_pct_moe_df_long.to_csv("county_languages_pct_moe_df_long.csv")
languages_lep_pct_moe_df_long.to_csv("county_languages_lep_pct_moe_df_long.csv")

In [17]:
languages_lep_pct_moe_df_long

,Geography,Geographic Area Name,language,lep_pct,moe_lep_pct_65_plus
0,0500000US24001,"Allegany County, Maryland",lep_pct_over_5,1.0,0.3
1,0500000US24003,"Anne Arundel County, Maryland",lep_pct_over_5,4.5,0.3
2,0500000US24005,"Baltimore County, Maryland",lep_pct_over_5,5.5,0.3
3,0500000US24009,"Calvert County, Maryland",lep_pct_over_5,1.5,0.5
4,0500000US24011,"Caroline County, Maryland",lep_pct_over_5,4.4,0.5
5,0500000US24013,"Carroll County, Maryland",lep_pct_over_5,1.9,0.3
6,0500000US24015,"Cecil County, Maryland",lep_pct_over_5,2.3,0.6
7,0500000US24017,"Charles County, Maryland",lep_pct_over_5,3.0,0.4
8,0500000US24019,"Dorchester County, Maryland",lep_pct_over_5,2.7,0.8
9,0500000US24021,"Frederick County, Maryland",lep_pct_over_5,5.6,0.4
10,0500000US24023,"Garrett County, Maryland",lep_pct_over_5,0.4,0.2
11,0500000US24025,"Harford County, Maryland",lep_pct_over_5,2.5,0.3
12,0500000US24027,"Howard County, Maryland",lep_pct_over_5,8.8,0.6
13,0500000US24029,"Kent County, Maryland",lep_pct_over_5,1.4,0.8
14,0500000US24031,"Montgomery County, Maryland",lep_pct_over_5,15.8,0.3
15,0500000US24033,"Prince George's County, Maryland",lep_pct_over_5,14.6,0.3
16,0500000US24035,"Queen Anne's County, Maryland",lep_pct_over_5,2.1,0.5
17,0500000US24037,"St. Mary's County, Maryland",lep_pct_over_5,2.6,0.7
18,0500000US24039,"Somerset County, Maryland",lep_pct_over_5,2.8,1.9
19,0500000US24041,"Talbot County, Maryland",lep_pct_over_5,4.5,1.0
20,0500000US24043,"Washington County, Maryland",lep_pct_over_5,3.3,0.5
21,0500000US24045,"Wicomico County, Maryland",lep_pct_over_5,6.5,1.1
22,0500000US24047,"Worcester County, Maryland",lep_pct_over_5,1.7,0.5
23,0500000US24510,"Baltimore city, Maryland",lep_pct_over_5,4.5,0.3
24,0500000US24001,"Allegany County, Maryland",lep_pct_spanish,34.8,12.2
25,0500000US24003,"Anne Arundel County, Maryland",lep_pct_spanish,37.6,3.0
26,0500000US24005,"Baltimore County, Maryland",lep_pct_spanish,39.8,3.3
27,0500000US24009,"Calvert County, Maryland",lep_pct_spanish,27.6,11.4
28,0500000US24011,"Caroline County, Maryland",lep_pct_spanish,58.2,6.9
29,0500000US24013,"Carroll County, Maryland",lep_pct_spanish,32.4,5.5
30,0500000US24015,"Cecil County, Maryland",lep_pct_spanish,29.0,9.4
31,0500000US24017,"Charles County, Maryland",lep_pct_spanish,35.9,6.0
32,0500000US24019,"Dorchester County, Maryland",lep_pct_spanish,46.9,11.9
33,0500000US24021,"Frederick County, Maryland",lep_pct_spanish,37.1,3.2
34,0500000US24023,"Garrett County, Maryland",lep_pct_spanish,30.8,18.2
35,0500000US24025,"Harford County, Maryland",lep_pct_spanish,37.0,5.8
36,0500000US24027,"Howard County, Maryland",lep_pct_spanish,39.6,4.3
37,0500000US24029,"Kent County, Maryland",lep_pct_spanish,29.5,15.0
38,0500000US24031,"Montgomery County, Maryland",lep_pct_spanish,43.4,1.2
39,0500000US24033,"Prince George's County, Maryland",lep_pct_spanish,57.4,1.3
40,0500000US24035,"Queen Anne's County, Maryland",lep_pct_spanish,44.2,10.3
41,0500000US24037,"St. Mary's County, Maryland",lep_pct_spanish,31.3,10.2
42,0500000US24039,"Somerset County, Maryland",lep_pct_spanish,26.2,8.4
43,0500000US24041,"Talbot County, Maryland",lep_pct_spanish,47.6,7.9
44,0500000US24043,"Washington County, Maryland",lep_pct_spanish,41.1,5.5
45,0500000US24045,"Wicomico County, Maryland",lep_pct_spanish,33.7,7.6
46,0500000US24047,"Worcester County, Maryland",lep_pct_spanish,35.6,8.9
47,0500000US24510,"Baltimore city, Maryland",lep_pct_spanish,44.3,3.0
48,0500000US24001,"Allegany County, Maryland",lep_pct_spanish_65_plus,19.7,17.0
49,0500000US24003,"Anne Arundel County, Maryland",lep_pct_spanish_65_plus,28.9,8.0
50,0500000US24005,"Baltimore County, Maryland",lep_pct_spanish_65_plus,38.3,7.8
51,0500000US24009,"Calvert County, Maryland",lep_pct_spanish_65_plus,86.2,19.7
52,0500000US24011,"Caroline County, Maryland",lep_pct_spanish_65_plus,23.1,28.1
53,0500000US24013,"Carroll County, Maryland",lep_pct_spanish_65_plus,8.8,11.1
54,0500000US24015,"Cecil County, Maryland",lep_pct_spanish_65_plus,27.5,27.2
55,0500000US24017,"Charles County, Maryland",lep_pct_spanish_65_plus,47.1,21.3
56,0500000US24019,"Dorchester County, Maryland",lep_pct_spanish_65_plus,74.7,38.1
57,0500000US24021,"Frederick County, Maryland",lep_pct_spanish_65_plus,51.4,10.2
58,0500000US24023,"Garrett County, Maryland",lep_pct_spanish_65_plus,11.8,35.1
59,0500000US24025,"Harford County, Maryland",lep_pct_spanish_65_plus,28.0,10.1
60,0500000US24027,"Howard County, Maryland",lep_pct_spanish_65_plus,43.4,14.2
61,0500000US24029,"Kent County, Maryland",lep_pct_spanish_65_plus,8.8,15.6
62,0500000US24031,"Montgomery County, Maryland",lep_pct_spanish_65_plus,62.3,3.6
63,0500000US24033,"Prince George's County, Maryland",lep_pct_spanish_65_plus,65.3,5.1
64,0500000US24035,"Queen Anne's County, Maryland",lep_pct_spanish_65_plus,28.6,23.8
65,0500000US24037,"St. Mary's County, Maryland",lep_pct_spanish_65_plus,37.4,19.7
66,0500000US24039,"Somerset County, Maryland",lep_pct_spanish_65_plus,0.0,54.3
67,0500000US24041,"Talbot County, Maryland",lep_pct_spanish_65_plus,25.9,20.4
68,0500000US24043,"Washington County, Maryland",lep_pct_spanish_65_plus,67.2,15.1
69,0500000US24045,"Wicomico County, Maryland",lep_pct_spanish_65_plus,2.3,4.7
70,0500000US24047,"Worcester County, Maryland",lep_pct_spanish_65_plus,15.8,17.0
71,0500000US24510,"Baltimore city, Maryland",lep_pct_spanish_65_plus,48.8,11.0
72,0500000US24001,"Allegany County, Maryland",lep_pct_indo_euro,12.1,8.3
73,0500000US24003,"Anne Arundel County, Maryland",lep_pct_indo_euro,24.3,2.4
74,0500000US24005,"Baltimore County, Maryland",lep_pct_indo_euro,33.9,2.6
75,0500000US24009,"Calvert County, Maryland",lep_pct_indo_euro,15.8,7.5
76,0500000US24011,"Caroline County, Maryland",lep_pct_indo_euro,18.3,17.2
77,0500000US24013,"Carroll County, Maryland",lep_pct_indo_euro,17.9,5.8
78,0500000US24015,"Cecil County, Maryland",lep_pct_indo_euro,31.9,10.4
79,0500000US24017,"Charles County, Maryland",lep_pct_indo_euro,30.4,5.7
80,0500000US24019,"Dorchester County, Maryland",lep_pct_indo_euro,33.2,29.6
81,0500000US24021,"Frederick County, Maryland",lep_pct_indo_euro,21.6,3.3
82,0500000US24023,"Garrett County, Maryland",lep_pct_indo_euro,2.5,3.8
83,0500000US24025,"Harford County, Maryland",lep_pct_indo_euro,17.7,3.8
84,0500000US24027,"Howard County, Maryland",lep_pct_indo_euro,22.0,2.8
85,0500000US24029,"Kent County, Maryland",lep_pct_indo_euro,25.4,12.0
86,0500000US24031,"Montgomery County, Maryland",lep_pct_indo_euro,27.2,1.5
87,0500000US24033,"Prince George's County, Maryland",lep_pct_indo_euro,33.2,2.9
88,0500000US24035,"Queen Anne's County, Maryland",lep_pct_indo_euro,15.6,10.7
89,0500000US24037,"St. Mary's County, Maryland",lep_pct_indo_euro,38.1,15.2
90,0500000US24039,"Somerset County, Maryland",lep_pct_indo_euro,17.0,34.1
91,0500000US24041,"Talbot County, Maryland",lep_pct_indo_euro,38.5,16.8
92,0500000US24043,"Washington County, Maryland",lep_pct_indo_euro,27.6,8.7
93,0500000US24045,"Wicomico County, Maryland",lep_pct_indo_euro,60.1,8.0
94,0500000US24047,"Worcester County, Maryland",lep_pct_indo_euro,15.4,7.4
95,0500000US24510,"Baltimore city, Maryland",lep_pct_indo_euro,26.9,4.5
96,0500000US24001,"Allegany County, Maryland",lep_pct_indo_euro_65_plus,19.9,19.0
97,0500000US24003,"Anne Arundel County, Maryland",lep_pct_indo_euro_65_plus,29.6,6.2
98,0500000US24005,"Baltimore County, Maryland",lep_pct_indo_euro_65_plus,51.6,5.3
99,0500000US24009,"Calvert County, Maryland",lep_pct_indo_euro_65_plus,40.8,30.8
100,0500000US24011,"Caroline County, Maryland",lep_pct_indo_euro_65_plus,13.3,23.3
101,0500000US24013,"Carroll County, Maryland",lep_pct_indo_euro_65_plus,33.1,13.7
102,0500000US24015,"Cecil County, Maryland",lep_pct_indo_euro_65_plus,49.8,28.3
103,0500000US24017,"Charles County, Maryland",lep_pct_indo_euro_65_plus,38.6,15.8
104,0500000US24019,"Dorchester County, Maryland",lep_pct_indo_euro_65_plus,47.3,41.8
105,0500000US24021,"Frederick County, Maryland",lep_pct_indo_euro_65_plus,36.3,12.9
106,0500000US24023,"Garrett County, Maryland",lep_pct_indo_euro_65_plus,6.1,10.7
107,0500000US24025,"Harford County, Maryland",lep_pct_indo_euro_65_plus,23.9,11.1
108,0500000US24027,"Howard County, Maryland",lep_pct_indo_euro_65_plus,39.2,7.8
109,0500000US24029,"Kent County, Maryland",lep_pct_indo_euro_65_plus,52.0,37.2
110,0500000US24031,"Montgomery County, Maryland",lep_pct_indo_euro_65_plus,39.2,3.2
111,0500000US24033,"Prince George's County, Maryland",lep_pct_indo_euro_65_plus,47.1,8.2
112,0500000US24035,"Queen Anne's County, Maryland",lep_pct_indo_euro_65_plus,21.0,14.9
113,0500000US24037,"St. Mary's County, Maryland",lep_pct_indo_euro_65_plus,22.7,20.7
114,0500000US24039,"Somerset County, Maryland",lep_pct_indo_euro_65_plus,69.2,69.2
115,0500000US24041,"Talbot County, Maryland",lep_pct_indo_euro_65_plus,49.7,27.5
116,0500000US24043,"Washington County, Maryland",lep_pct_indo_euro_65_plus,17.8,9.9
117,0500000US24045,"Wicomico County, Maryland",lep_pct_indo_euro_65_plus,31.5,17.0
118,0500000US24047,"Worcester County, Maryland",lep_pct_indo_euro_65_plus,15.3,11.5
119,0500000US24510,"Baltimore city, Maryland",lep_pct_indo_euro_65_plus,36.7,8.8
120,0500000US24001,"Allegany County, Maryland",lep_pct_asian_pacific,52.6,15.0
121,0500000US24003,"Anne Arundel County, Maryland",lep_pct_asian_pacific,39.9,4.0
122,0500000US24005,"Baltimore County, Maryland",lep_pct_asian_pacific,39.7,2.9
123,0500000US24009,"Calvert County, Maryland",lep_pct_asian_pacific,37.4,11.8
124,0500000US24011,"Caroline County, Maryland",lep_pct_asian_pacific,55.6,51.3
125,0500000US24013,"Carroll County, Maryland",lep_pct_asian_pacific,37.9,10.3
126,0500000US24015,"Cecil County, Maryland",lep_pct_asian_pacific,39.6,13.7
127,0500000US24017,"Charles County, Maryland",lep_pct_asian_pacific,27.9,7.8
128,0500000US24019,"Dorchester County, Maryland",lep_pct_asian_pacific,62.3,27.2
129,0500000US24021,"Frederick County, Maryland",lep_pct_asian_pacific,34.9,4.6
130,0500000US24023,"Garrett County, Maryland",lep_pct_asian_pacific,14.2,20.5
131,0500000US24025,"Harford County, Maryland",lep_pct_asian_pacific,37.7,5.5
132,0500000US24027,"Howard County, Maryland",lep_pct_asian_pacific,37.0,2.5
133,0500000US24029,"Kent County, Maryland",lep_pct_asian_pacific,18.4,32.1
134,0500000US24031,"Montgomery County, Maryland",lep_pct_asian_pacific,41.6,1.5
135,0500000US24033,"Prince George's County, Maryland",lep_pct_asian_pacific,40.1,3.4
136,0500000US24035,"Queen Anne's County, Maryland",lep_pct_asian_pacific,44.8,30.6
137,0500000US24037,"St. Mary's County, Maryland",lep_pct_asian_pacific,42.2,11.3
138,0500000US24039,"Somerset County, Maryland",lep_pct_asian_pacific,0.0,55.8
139,0500000US24041,"Talbot County, Maryland",lep_pct_asian_pacific,38.6,17.0
140,0500000US24043,"Washington County, Maryland",lep_pct_asian_pacific,37.8,12.5
141,0500000US24045,"Wicomico County, Maryland",lep_pct_asian_pacific,43.7,12.0
142,0500000US24047,"Worcester County, Maryland",lep_pct_asian_pacific,34.7,16.1
143,0500000US24510,"Baltimore city, Maryland",lep_pct_asian_pacific,38.1,3.8
144,0500000US24001,"Allegany County, Maryland",lep_pct_asian_pacific_65_plus,25.0,42.4
145,0500000US24003,"Anne Arundel County, Maryland",lep_pct_asian_pacific_65_plus,55.7,11.6
146,0500000US24005,"Baltimore County, Maryland",lep_pct_asian_pacific_65_plus,60.3,6.1
147,0500000US24009,"Calvert County, Maryland",lep_pct_asian_pacific_65_plus,60.3,27.6
148,0500000US24011,"Caroline County, Maryland",lep_pct_asian_pacific_65_plus,0.0,100.0
149,0500000US24013,"Carroll County, Maryland",lep_pct_asian_pacific_65_plus,58.3,14.9
150,0500000US24015,"Cecil County, Maryland",lep_pct_asian_pacific_65_plus,31.3,30.9
151,0500000US24017,"Charles County, Maryland",lep_pct_asian_pacific_65_plus,26.7,14.0
152,0500000US24019,"Dorchester County, Maryland",lep_pct_asian_pacific_65_plus,76.7,36.4
153,0500000US24021,"Frederick County, Maryland",lep_pct_asian_pacific_65_plus,51.7,16.3
154,0500000US24023,"Garrett County, Maryland",lep_pct_asian_pacific_65_plus,0.0,100.0
155,0500000US24025,"Harford County, Maryland",lep_pct_asian_pacific_65_plus,64.1,13.7
156,0500000US24027,"Howard County, Maryland",lep_pct_asian_pacific_65_plus,66.4,6.4
157,0500000US24029,"Kent County, Maryland",lep_pct_asian_pacific_65_plus,-,**
158,0500000US24031,"Montgomery County, Maryland",lep_pct_asian_pacific_65_plus,64.4,3.3
159,0500000US24033,"Prince George's County, Maryland",lep_pct_asian_pacific_65_plus,51.1,9.3
160,0500000US24035,"Queen Anne's County, Maryland",lep_pct_asian_pacific_65_plus,25.2,33.4
161,0500000US24037,"St. Mary's County, Maryland",lep_pct_asian_pacific_65_plus,74.6,20.2
162,0500000US24039,"Somerset County, Maryland",lep_pct_asian_pacific_65_plus,-,**
163,0500000US24041,"Talbot County, Maryland",lep_pct_asian_pacific_65_plus,93.5,12.5
164,0500000US24043,"Washington County, Maryland",lep_pct_asian_pacific_65_plus,22.0,17.3
165,0500000US24045,"Wicomico County, Maryland",lep_pct_asian_pacific_65_plus,93.4,8.5
166,0500000US24047,"Worcester County, Maryland",lep_pct_asian_pacific_65_plus,100.0,100.0
167,0500000US24510,"Baltimore city, Maryland",lep_pct_asian_pacific_65_plus,66.2,15.4
168,0500000US24001,"Allegany County, Maryland",lep_pct_other,11.9,17.3
169,0500000US24003,"Anne Arundel County, Maryland",lep_pct_other,12.9,4.2
170,0500000US24005,"Baltimore County, Maryland",lep_pct_other,24.4,3.3
171,0500000US24009,"Calvert County, Maryland",lep_pct_other,15.7,15.8
172,0500000US24011,"Caroline County, Maryland",lep_pct_other,3.5,15.8
173,0500000US24013,"Carroll County, Maryland",lep_pct_other,20.4,13.7
174,0500000US24015,"Cecil County, Maryland",lep_pct_other,43.2,19.2
175,0500000US24017,"Charles County, Maryland",lep_pct_other,8.1,4.7
176,0500000US24019,"Dorchester County, Maryland",lep_pct_other,0.0,43.8
177,0500000US24021,"Frederick County, Maryland",lep_pct_other,23.1,5.3
178,0500000US24023,"Garrett County, Maryland",lep_pct_other,-,**
179,0500000US24025,"Harford County, Maryland",lep_pct_other,21.5,7.0
180,0500000US24027,"Howard County, Maryland",lep_pct_other,18.4,3.5
181,0500000US24029,"Kent County, Maryland",lep_pct_other,6.7,12.1
182,0500000US24031,"Montgomery County, Maryland",lep_pct_other,25.8,1.9
183,0500000US24033,"Prince George's County, Maryland",lep_pct_other,22.6,2.3
184,0500000US24035,"Queen Anne's County, Maryland",lep_pct_other,12.2,9.1
185,0500000US24037,"St. Mary's County, Maryland",lep_pct_other,13.4,13.2
186,0500000US24039,"Somerset County, Maryland",lep_pct_other,58.8,26.4
187,0500000US24041,"Talbot County, Maryland",lep_pct_other,60.7,22.9
188,0500000US24043,"Washington County, Maryland",lep_pct_other,10.8,6.9
189,0500000US24045,"Wicomico County, Maryland",lep_pct_other,31.5,22.6
190,0500000US24047,"Worcester County, Maryland",lep_pct_other,51.9,40.3
191,0500000US24510,"Baltimore city, Maryland",lep_pct_other,31.4,7.6
192,0500000US24001,"Allegany County, Maryland",lep_pct_other_65_plus,0.0,100.0
193,0500000US24003,"Anne Arundel County, Maryland",lep_pct_other_65_plus,17.3,13.6
194,0500000US24005,"Baltimore County, Maryland",lep_pct_other_65_plus,28.9,9.2
195,0500000US24009,"Calvert County, Maryland",lep_pct_other_65_plus,40.5,51.2
196,0500000US24011,"Caroline County, Maryland",lep_pct_other_65_plus,100.0,100.0
197,0500000US24013,"Carroll County, Maryland",lep_pct_other_65_plus,13.2,21.5
198,0500000US24015,"Cecil County, Maryland",lep_pct_other_65_plus,60.5,43.0
199,0500000US24017,"Charles County, Maryland",lep_pct_other_65_plus,33.3,28.8
200,0500000US24019,"Dorchester County, Maryland",lep_pct_other_65_plus,0.0,100.0
201,0500000US24021,"Frederick County, Maryland",lep_pct_other_65_plus,57.6,15.0
202,0500000US24023,"Garrett County, Maryland",lep_pct_other_65_plus,-,**
203,0500000US24025,"Harford County, Maryland",lep_pct_other_65_plus,59.5,27.7
204,0500000US24027,"Howard County, Maryland",lep_pct_other_65_plus,34.5,13.5
205,0500000US24029,"Kent County, Maryland",lep_pct_other_65_plus,-,**
206,0500000US24031,"Montgomery County, Maryland",lep_pct_other_65_plus,31.9,5.6
207,0500000US24033,"Prince George's County, Maryland",lep_pct_other_65_plus,33.3,5.4
208,0500000US24035,"Queen Anne's County, Maryland",lep_pct_other_65_plus,0.0,100.0
209,0500000US24037,"St. Mary's County, Maryland",lep_pct_other_65_plus,0.0,61.9
210,0500000US24039,"Somerset County, Maryland",lep_pct_other_65_plus,100.0,44.9
211,0500000US24041,"Talbot County, Maryland",lep_pct_other_65_plus,13.3,41.4
212,0500000US24043,"Washington County, Maryland",lep_pct_other_65_plus,0.0,34.0
213,0500000US24045,"Wicomico County, Maryland",lep_pct_other_65_plus,0.0,100.0
214,0500000US24047,"Worcester County, Maryland",lep_pct_other_65_plus,0.0,90.6
215,0500000US24510,"Baltimore city, Maryland",lep_pct_other_65_plus,26.0,17.5

In [18]:
import numpy as np
languages_lep_pct_moe_df_long.replace({'-': np.nan},inplace =True)

,Geography,Geographic Area Name,language,lep_pct,moe_lep_pct_65_plus
0,0500000US24001,"Allegany County, Maryland",lep_pct_over_5,1.0,0.3
1,0500000US24003,"Anne Arundel County, Maryland",lep_pct_over_5,4.5,0.3
2,0500000US24005,"Baltimore County, Maryland",lep_pct_over_5,5.5,0.3
3,0500000US24009,"Calvert County, Maryland",lep_pct_over_5,1.5,0.5
4,0500000US24011,"Caroline County, Maryland",lep_pct_over_5,4.4,0.5
5,0500000US24013,"Carroll County, Maryland",lep_pct_over_5,1.9,0.3
6,0500000US24015,"Cecil County, Maryland",lep_pct_over_5,2.3,0.6
7,0500000US24017,"Charles County, Maryland",lep_pct_over_5,3.0,0.4
8,0500000US24019,"Dorchester County, Maryland",lep_pct_over_5,2.7,0.8
9,0500000US24021,"Frederick County, Maryland",lep_pct_over_5,5.6,0.4
10,0500000US24023,"Garrett County, Maryland",lep_pct_over_5,0.4,0.2
11,0500000US24025,"Harford County, Maryland",lep_pct_over_5,2.5,0.3
12,0500000US24027,"Howard County, Maryland",lep_pct_over_5,8.8,0.6
13,0500000US24029,"Kent County, Maryland",lep_pct_over_5,1.4,0.8
14,0500000US24031,"Montgomery County, Maryland",lep_pct_over_5,15.8,0.3
15,0500000US24033,"Prince George's County, Maryland",lep_pct_over_5,14.6,0.3
16,0500000US24035,"Queen Anne's County, Maryland",lep_pct_over_5,2.1,0.5
17,0500000US24037,"St. Mary's County, Maryland",lep_pct_over_5,2.6,0.7
18,0500000US24039,"Somerset County, Maryland",lep_pct_over_5,2.8,1.9
19,0500000US24041,"Talbot County, Maryland",lep_pct_over_5,4.5,1.0
20,0500000US24043,"Washington County, Maryland",lep_pct_over_5,3.3,0.5
21,0500000US24045,"Wicomico County, Maryland",lep_pct_over_5,6.5,1.1
22,0500000US24047,"Worcester County, Maryland",lep_pct_over_5,1.7,0.5
23,0500000US24510,"Baltimore city, Maryland",lep_pct_over_5,4.5,0.3
24,0500000US24001,"Allegany County, Maryland",lep_pct_spanish,34.8,12.2
25,0500000US24003,"Anne Arundel County, Maryland",lep_pct_spanish,37.6,3.0
26,0500000US24005,"Baltimore County, Maryland",lep_pct_spanish,39.8,3.3
27,0500000US24009,"Calvert County, Maryland",lep_pct_spanish,27.6,11.4
28,0500000US24011,"Caroline County, Maryland",lep_pct_spanish,58.2,6.9
29,0500000US24013,"Carroll County, Maryland",lep_pct_spanish,32.4,5.5
30,0500000US24015,"Cecil County, Maryland",lep_pct_spanish,29.0,9.4
31,0500000US24017,"Charles County, Maryland",lep_pct_spanish,35.9,6.0
32,0500000US24019,"Dorchester County, Maryland",lep_pct_spanish,46.9,11.9
33,0500000US24021,"Frederick County, Maryland",lep_pct_spanish,37.1,3.2
34,0500000US24023,"Garrett County, Maryland",lep_pct_spanish,30.8,18.2
35,0500000US24025,"Harford County, Maryland",lep_pct_spanish,37.0,5.8
36,0500000US24027,"Howard County, Maryland",lep_pct_spanish,39.6,4.3
37,0500000US24029,"Kent County, Maryland",lep_pct_spanish,29.5,15.0
38,0500000US24031,"Montgomery County, Maryland",lep_pct_spanish,43.4,1.2
39,0500000US24033,"Prince George's County, Maryland",lep_pct_spanish,57.4,1.3
40,0500000US24035,"Queen Anne's County, Maryland",lep_pct_spanish,44.2,10.3
41,0500000US24037,"St. Mary's County, Maryland",lep_pct_spanish,31.3,10.2
42,0500000US24039,"Somerset County, Maryland",lep_pct_spanish,26.2,8.4
43,0500000US24041,"Talbot County, Maryland",lep_pct_spanish,47.6,7.9
44,0500000US24043,"Washington County, Maryland",lep_pct_spanish,41.1,5.5
45,0500000US24045,"Wicomico County, Maryland",lep_pct_spanish,33.7,7.6
46,0500000US24047,"Worcester County, Maryland",lep_pct_spanish,35.6,8.9
47,0500000US24510,"Baltimore city, Maryland",lep_pct_spanish,44.3,3.0
48,0500000US24001,"Allegany County, Maryland",lep_pct_spanish_65_plus,19.7,17.0
49,0500000US24003,"Anne Arundel County, Maryland",lep_pct_spanish_65_plus,28.9,8.0
50,0500000US24005,"Baltimore County, Maryland",lep_pct_spanish_65_plus,38.3,7.8
51,0500000US24009,"Calvert County, Maryland",lep_pct_spanish_65_plus,86.2,19.7
52,0500000US24011,"Caroline County, Maryland",lep_pct_spanish_65_plus,23.1,28.1
53,0500000US24013,"Carroll County, Maryland",lep_pct_spanish_65_plus,8.8,11.1
54,0500000US24015,"Cecil County, Maryland",lep_pct_spanish_65_plus,27.5,27.2
55,0500000US24017,"Charles County, Maryland",lep_pct_spanish_65_plus,47.1,21.3
56,0500000US24019,"Dorchester County, Maryland",lep_pct_spanish_65_plus,74.7,38.1
57,0500000US24021,"Frederick County, Maryland",lep_pct_spanish_65_plus,51.4,10.2
58,0500000US24023,"Garrett County, Maryland",lep_pct_spanish_65_plus,11.8,35.1
59,0500000US24025,"Harford County, Maryland",lep_pct_spanish_65_plus,28.0,10.1
60,0500000US24027,"Howard County, Maryland",lep_pct_spanish_65_plus,43.4,14.2
61,0500000US24029,"Kent County, Maryland",lep_pct_spanish_65_plus,8.8,15.6
62,0500000US24031,"Montgomery County, Maryland",lep_pct_spanish_65_plus,62.3,3.6
63,0500000US24033,"Prince George's County, Maryland",lep_pct_spanish_65_plus,65.3,5.1
64,0500000US24035,"Queen Anne's County, Maryland",lep_pct_spanish_65_plus,28.6,23.8
65,0500000US24037,"St. Mary's County, Maryland",lep_pct_spanish_65_plus,37.4,19.7
66,0500000US24039,"Somerset County, Maryland",lep_pct_spanish_65_plus,0.0,54.3
67,0500000US24041,"Talbot County, Maryland",lep_pct_spanish_65_plus,25.9,20.4
68,0500000US24043,"Washington County, Maryland",lep_pct_spanish_65_plus,67.2,15.1
69,0500000US24045,"Wicomico County, Maryland",lep_pct_spanish_65_plus,2.3,4.7
70,0500000US24047,"Worcester County, Maryland",lep_pct_spanish_65_plus,15.8,17.0
71,0500000US24510,"Baltimore city, Maryland",lep_pct_spanish_65_plus,48.8,11.0
72,0500000US24001,"Allegany County, Maryland",lep_pct_indo_euro,12.1,8.3
73,0500000US24003,"Anne Arundel County, Maryland",lep_pct_indo_euro,24.3,2.4
74,0500000US24005,"Baltimore County, Maryland",lep_pct_indo_euro,33.9,2.6
75,0500000US24009,"Calvert County, Maryland",lep_pct_indo_euro,15.8,7.5
76,0500000US24011,"Caroline County, Maryland",lep_pct_indo_euro,18.3,17.2
77,0500000US24013,"Carroll County, Maryland",lep_pct_indo_euro,17.9,5.8
78,0500000US24015,"Cecil County, Maryland",lep_pct_indo_euro,31.9,10.4
79,0500000US24017,"Charles County, Maryland",lep_pct_indo_euro,30.4,5.7
80,0500000US24019,"Dorchester County, Maryland",lep_pct_indo_euro,33.2,29.6
81,0500000US24021,"Frederick County, Maryland",lep_pct_indo_euro,21.6,3.3
82,0500000US24023,"Garrett County, Maryland",lep_pct_indo_euro,2.5,3.8
83,0500000US24025,"Harford County, Maryland",lep_pct_indo_euro,17.7,3.8
84,0500000US24027,"Howard County, Maryland",lep_pct_indo_euro,22.0,2.8
85,0500000US24029,"Kent County, Maryland",lep_pct_indo_euro,25.4,12.0
86,0500000US24031,"Montgomery County, Maryland",lep_pct_indo_euro,27.2,1.5
87,0500000US24033,"Prince George's County, Maryland",lep_pct_indo_euro,33.2,2.9
88,0500000US24035,"Queen Anne's County, Maryland",lep_pct_indo_euro,15.6,10.7
89,0500000US24037,"St. Mary's County, Maryland",lep_pct_indo_euro,38.1,15.2
90,0500000US24039,"Somerset County, Maryland",lep_pct_indo_euro,17.0,34.1
91,0500000US24041,"Talbot County, Maryland",lep_pct_indo_euro,38.5,16.8
92,0500000US24043,"Washington County, Maryland",lep_pct_indo_euro,27.6,8.7
93,0500000US24045,"Wicomico County, Maryland",lep_pct_indo_euro,60.1,8.0
94,0500000US24047,"Worcester County, Maryland",lep_pct_indo_euro,15.4,7.4
95,0500000US24510,"Baltimore city, Maryland",lep_pct_indo_euro,26.9,4.5
96,0500000US24001,"Allegany County, Maryland",lep_pct_indo_euro_65_plus,19.9,19.0
97,0500000US24003,"Anne Arundel County, Maryland",lep_pct_indo_euro_65_plus,29.6,6.2
98,0500000US24005,"Baltimore County, Maryland",lep_pct_indo_euro_65_plus,51.6,5.3
99,0500000US24009,"Calvert County, Maryland",lep_pct_indo_euro_65_plus,40.8,30.8
100,0500000US24011,"Caroline County, Maryland",lep_pct_indo_euro_65_plus,13.3,23.3
101,0500000US24013,"Carroll County, Maryland",lep_pct_indo_euro_65_plus,33.1,13.7
102,0500000US24015,"Cecil County, Maryland",lep_pct_indo_euro_65_plus,49.8,28.3
103,0500000US24017,"Charles County, Maryland",lep_pct_indo_euro_65_plus,38.6,15.8
104,0500000US24019,"Dorchester County, Maryland",lep_pct_indo_euro_65_plus,47.3,41.8
105,0500000US24021,"Frederick County, Maryland",lep_pct_indo_euro_65_plus,36.3,12.9
106,0500000US24023,"Garrett County, Maryland",lep_pct_indo_euro_65_plus,6.1,10.7
107,0500000US24025,"Harford County, Maryland",lep_pct_indo_euro_65_plus,23.9,11.1
108,0500000US24027,"Howard County, Maryland",lep_pct_indo_euro_65_plus,39.2,7.8
109,0500000US24029,"Kent County, Maryland",lep_pct_indo_euro_65_plus,52.0,37.2
110,0500000US24031,"Montgomery County, Maryland",lep_pct_indo_euro_65_plus,39.2,3.2
111,0500000US24033,"Prince George's County, Maryland",lep_pct_indo_euro_65_plus,47.1,8.2
112,0500000US24035,"Queen Anne's County, Maryland",lep_pct_indo_euro_65_plus,21.0,14.9
113,0500000US24037,"St. Mary's County, Maryland",lep_pct_indo_euro_65_plus,22.7,20.7
114,0500000US24039,"Somerset County, Maryland",lep_pct_indo_euro_65_plus,69.2,69.2
115,0500000US24041,"Talbot County, Maryland",lep_pct_indo_euro_65_plus,49.7,27.5
116,0500000US24043,"Washington County, Maryland",lep_pct_indo_euro_65_plus,17.8,9.9
117,0500000US24045,"Wicomico County, Maryland",lep_pct_indo_euro_65_plus,31.5,17.0
118,0500000US24047,"Worcester County, Maryland",lep_pct_indo_euro_65_plus,15.3,11.5
119,0500000US24510,"Baltimore city, Maryland",lep_pct_indo_euro_65_plus,36.7,8.8
120,0500000US24001,"Allegany County, Maryland",lep_pct_asian_pacific,52.6,15.0
121,0500000US24003,"Anne Arundel County, Maryland",lep_pct_asian_pacific,39.9,4.0
122,0500000US24005,"Baltimore County, Maryland",lep_pct_asian_pacific,39.7,2.9
123,0500000US24009,"Calvert County, Maryland",lep_pct_asian_pacific,37.4,11.8
124,0500000US24011,"Caroline County, Maryland",lep_pct_asian_pacific,55.6,51.3
125,0500000US24013,"Carroll County, Maryland",lep_pct_asian_pacific,37.9,10.3
126,0500000US24015,"Cecil County, Maryland",lep_pct_asian_pacific,39.6,13.7
127,0500000US24017,"Charles County, Maryland",lep_pct_asian_pacific,27.9,7.8
128,0500000US24019,"Dorchester County, Maryland",lep_pct_asian_pacific,62.3,27.2
129,0500000US24021,"Frederick County, Maryland",lep_pct_asian_pacific,34.9,4.6
130,0500000US24023,"Garrett County, Maryland",lep_pct_asian_pacific,14.2,20.5
131,0500000US24025,"Harford County, Maryland",lep_pct_asian_pacific,37.7,5.5
132,0500000US24027,"Howard County, Maryland",lep_pct_asian_pacific,37.0,2.5
133,0500000US24029,"Kent County, Maryland",lep_pct_asian_pacific,18.4,32.1
134,0500000US24031,"Montgomery County, Maryland",lep_pct_asian_pacific,41.6,1.5
135,0500000US24033,"Prince George's County, Maryland",lep_pct_asian_pacific,40.1,3.4
136,0500000US24035,"Queen Anne's County, Maryland",lep_pct_asian_pacific,44.8,30.6
137,0500000US24037,"St. Mary's County, Maryland",lep_pct_asian_pacific,42.2,11.3
138,0500000US24039,"Somerset County, Maryland",lep_pct_asian_pacific,0.0,55.8
139,0500000US24041,"Talbot County, Maryland",lep_pct_asian_pacific,38.6,17.0
140,0500000US24043,"Washington County, Maryland",lep_pct_asian_pacific,37.8,12.5
141,0500000US24045,"Wicomico County, Maryland",lep_pct_asian_pacific,43.7,12.0
142,0500000US24047,"Worcester County, Maryland",lep_pct_asian_pacific,34.7,16.1
143,0500000US24510,"Baltimore city, Maryland",lep_pct_asian_pacific,38.1,3.8
144,0500000US24001,"Allegany County, Maryland",lep_pct_asian_pacific_65_plus,25.0,42.4
145,0500000US24003,"Anne Arundel County, Maryland",lep_pct_asian_pacific_65_plus,55.7,11.6
146,0500000US24005,"Baltimore County, Maryland",lep_pct_asian_pacific_65_plus,60.3,6.1
147,0500000US24009,"Calvert County, Maryland",lep_pct_asian_pacific_65_plus,60.3,27.6
148,0500000US24011,"Caroline County, Maryland",lep_pct_asian_pacific_65_plus,0.0,100.0
149,0500000US24013,"Carroll County, Maryland",lep_pct_asian_pacific_65_plus,58.3,14.9
150,0500000US24015,"Cecil County, Maryland",lep_pct_asian_pacific_65_plus,31.3,30.9
151,0500000US24017,"Charles County, Maryland",lep_pct_asian_pacific_65_plus,26.7,14.0
152,0500000US24019,"Dorchester County, Maryland",lep_pct_asian_pacific_65_plus,76.7,36.4
153,0500000US24021,"Frederick County, Maryland",lep_pct_asian_pacific_65_plus,51.7,16.3
154,0500000US24023,"Garrett County, Maryland",lep_pct_asian_pacific_65_plus,0.0,100.0
155,0500000US24025,"Harford County, Maryland",lep_pct_asian_pacific_65_plus,64.1,13.7
156,0500000US24027,"Howard County, Maryland",lep_pct_asian_pacific_65_plus,66.4,6.4
157,0500000US24029,"Kent County, Maryland",lep_pct_asian_pacific_65_plus,NaN,**
158,0500000US24031,"Montgomery County, Maryland",lep_pct_asian_pacific_65_plus,64.4,3.3
159,0500000US24033,"Prince George's County, Maryland",lep_pct_asian_pacific_65_plus,51.1,9.3
160,0500000US24035,"Queen Anne's County, Maryland",lep_pct_asian_pacific_65_plus,25.2,33.4
161,0500000US24037,"St. Mary's County, Maryland",lep_pct_asian_pacific_65_plus,74.6,20.2
162,0500000US24039,"Somerset County, Maryland",lep_pct_asian_pacific_65_plus,NaN,**
163,0500000US24041,"Talbot County, Maryland",lep_pct_asian_pacific_65_plus,93.5,12.5
164,0500000US24043,"Washington County, Maryland",lep_pct_asian_pacific_65_plus,22.0,17.3
165,0500000US24045,"Wicomico County, Maryland",lep_pct_asian_pacific_65_plus,93.4,8.5
166,0500000US24047,"Worcester County, Maryland",lep_pct_asian_pacific_65_plus,100.0,100.0
167,0500000US24510,"Baltimore city, Maryland",lep_pct_asian_pacific_65_plus,66.2,15.4
168,0500000US24001,"Allegany County, Maryland",lep_pct_other,11.9,17.3
169,0500000US24003,"Anne Arundel County, Maryland",lep_pct_other,12.9,4.2
170,0500000US24005,"Baltimore County, Maryland",lep_pct_other,24.4,3.3
171,0500000US24009,"Calvert County, Maryland",lep_pct_other,15.7,15.8
172,0500000US24011,"Caroline County, Maryland",lep_pct_other,3.5,15.8
173,0500000US24013,"Carroll County, Maryland",lep_pct_other,20.4,13.7
174,0500000US24015,"Cecil County, Maryland",lep_pct_other,43.2,19.2
175,0500000US24017,"Charles County, Maryland",lep_pct_other,8.1,4.7
176,0500000US24019,"Dorchester County, Maryland",lep_pct_other,0.0,43.8
177,0500000US24021,"Frederick County, Maryland",lep_pct_other,23.1,5.3
178,0500000US24023,"Garrett County, Maryland",lep_pct_other,NaN,**
179,0500000US24025,"Harford County, Maryland",lep_pct_other,21.5,7.0
180,0500000US24027,"Howard County, Maryland",lep_pct_other,18.4,3.5
181,0500000US24029,"Kent County, Maryland",lep_pct_other,6.7,12.1
182,0500000US24031,"Montgomery County, Maryland",lep_pct_other,25.8,1.9
183,0500000US24033,"Prince George's County, Maryland",lep_pct_other,22.6,2.3
184,0500000US24035,"Queen Anne's County, Maryland",lep_pct_other,12.2,9.1
185,0500000US24037,"St. Mary's County, Maryland",lep_pct_other,13.4,13.2
186,0500000US24039,"Somerset County, Maryland",lep_pct_other,58.8,26.4
187,0500000US24041,"Talbot County, Maryland",lep_pct_other,60.7,22.9
188,0500000US24043,"Washington County, Maryland",lep_pct_other,10.8,6.9
189,0500000US24045,"Wicomico County, Maryland",lep_pct_other,31.5,22.6
190,0500000US24047,"Worcester County, Maryland",lep_pct_other,51.9,40.3
191,0500000US24510,"Baltimore city, Maryland",lep_pct_other,31.4,7.6
192,0500000US24001,"Allegany County, Maryland",lep_pct_other_65_plus,0.0,100.0
193,0500000US24003,"Anne Arundel County, Maryland",lep_pct_other_65_plus,17.3,13.6
194,0500000US24005,"Baltimore County, Maryland",lep_pct_other_65_plus,28.9,9.2
195,0500000US24009,"Calvert County, Maryland",lep_pct_other_65_plus,40.5,51.2
196,0500000US24011,"Caroline County, Maryland",lep_pct_other_65_plus,100.0,100.0
197,0500000US24013,"Carroll County, Maryland",lep_pct_other_65_plus,13.2,21.5
198,0500000US24015,"Cecil County, Maryland",lep_pct_other_65_plus,60.5,43.0
199,0500000US24017,"Charles County, Maryland",lep_pct_other_65_plus,33.3,28.8
200,0500000US24019,"Dorchester County, Maryland",lep_pct_other_65_plus,0.0,100.0
201,0500000US24021,"Frederick County, Maryland",lep_pct_other_65_plus,57.6,15.0
202,0500000US24023,"Garrett County, Maryland",lep_pct_other_65_plus,NaN,**
203,0500000US24025,"Harford County, Maryland",lep_pct_other_65_plus,59.5,27.7
204,0500000US24027,"Howard County, Maryland",lep_pct_other_65_plus,34.5,13.5
205,0500000US24029,"Kent County, Maryland",lep_pct_other_65_plus,NaN,**
206,0500000US24031,"Montgomery County, Maryland",lep_pct_other_65_plus,31.9,5.6
207,0500000US24033,"Prince George's County, Maryland",lep_pct_other_65_plus,33.3,5.4
208,0500000US24035,"Queen Anne's County, Maryland",lep_pct_other_65_plus,0.0,100.0
209,0500000US24037,"St. Mary's County, Maryland",lep_pct_other_65_plus,0.0,61.9
210,0500000US24039,"Somerset County, Maryland",lep_pct_other_65_plus,100.0,44.9
211,0500000US24041,"Talbot County, Maryland",lep_pct_other_65_plus,13.3,41.4
212,0500000US24043,"Washington County, Maryland",lep_pct_other_65_plus,0.0,34.0
213,0500000US24045,"Wicomico County, Maryland",lep_pct_other_65_plus,0.0,100.0
214,0500000US24047,"Worcester County, Maryland",lep_pct_other_65_plus,0.0,90.6
215,0500000US24510,"Baltimore city, Maryland",lep_pct_other_65_plus,26.0,17.5

In [19]:
languages_lep_pct_moe_df_long['lep_pct']=languages_lep_pct_moe_df_long['lep_pct'].astype(float)

In [20]:
languages_lep_pct_moe_df_long_wide = languages_lep_pct_moe_df_long.pivot(
    index='Geographic Area Name',
    columns='language',
    values='lep_pct'
).reset_index()

In [21]:
languages_lep_pct_moe_df_long_wide.to_csv("languages_county_lep_pct_moe_df_long_wide.csv")

In [22]:
#County populations from 5-year 2024 ASC
#How many people over 65 in the county? 
#Percentage of people over 65 in the county?

In [23]:
county_65_plus_pop_official_df=pd.read_csv("county_65_plus_pop_official_df.csv")

In [24]:
county_65_plus_pop_official_df.head()

,Unnamed: 0,Geography,Geographic Area Name,Estimate!!Total:,Estimate!!Total:!!Male:!!65 and 66 years,Margin of Error!!Total:!!Male:!!65 and 66 years,Estimate!!Total:!!Male:!!67 to 69 years,Margin of Error!!Total:!!Male:!!67 to 69 years,Estimate!!Total:!!Male:!!70 to 74 years,Margin of Error!!Total:!!Male:!!70 to 74 years,...,Estimate!!Total:!!Female:!!67 to 69 years,Margin of Error!!Total:!!Female:!!67 to 69 years,Estimate!!Total:!!Female:!!70 to 74 years,Margin of Error!!Total:!!Female:!!70 to 74 years,Estimate!!Total:!!Female:!!75 to 79 years,Margin of Error!!Total:!!Female:!!75 to 79 years,Estimate!!Total:!!Female:!!80 to 84 years,Margin of Error!!Total:!!Female:!!80 to 84 years,Estimate!!Total:!!Female:!!85 years and over,Margin of Error!!Total:!!Female:!!85 years and over
0,1,0500000US24001,"Allegany County, Maryland",67452,836,167,912,142,2069,182,...,925,148,2415,186,1273,140,1140,193,1251,177
1,2,0500000US24003,"Anne Arundel County, Maryland",598166,5640,546,8299,640,12208,636,...,9263,578,13490,653,9512,556,6634,529,6294,550
2,3,0500000US24005,"Baltimore County, Maryland",850796,8778,661,13129,781,18567,827,...,16014,800,22859,777,15777,772,10899,595,12745,811
3,4,0500000US24009,"Calvert County, Maryland",94313,1255,221,1420,224,1634,235,...,1494,277,2244,234,1835,201,760,165,987,208
4,5,0500000US24011,"Caroline County, Maryland",33669,344,105,527,132,822,150,...,527,94,909,120,579,133,258,93,543,139

In [25]:
#County populations from 5-year 2024 ASC = 6206011
county_65_plus_pop_official_df['Estimate!!Total:'].sum()

np.int64(6206011)

In [26]:
county_65_plus_pop_official_df.columns.tolist()

['Unnamed: 0',
 'Geography',
 'Geographic Area Name',
 'Estimate!!Total:',
 'Estimate!!Total:!!Male:!!65 and 66 years',
 'Margin of Error!!Total:!!Male:!!65 and 66 years',
 'Estimate!!Total:!!Male:!!67 to 69 years',
 'Margin of Error!!Total:!!Male:!!67 to 69 years',
 'Estimate!!Total:!!Male:!!70 to 74 years',
 'Margin of Error!!Total:!!Male:!!70 to 74 years',
 'Estimate!!Total:!!Male:!!75 to 79 years',
 'Margin of Error!!Total:!!Male:!!75 to 79 years',
 'Estimate!!Total:!!Male:!!80 to 84 years',
 'Margin of Error!!Total:!!Male:!!80 to 84 years',
 'Estimate!!Total:!!Male:!!85 years and over',
 'Margin of Error!!Total:!!Male:!!85 years and over',
 'Estimate!!Total:!!Female:!!65 and 66 years',
 'Margin of Error!!Total:!!Female:!!65 and 66 years',
 'Estimate!!Total:!!Female:!!67 to 69 years',
 'Margin of Error!!Total:!!Female:!!67 to 69 years',
 'Estimate!!Total:!!Female:!!70 to 74 years',
 'Margin of Error!!Total:!!Female:!!70 to 74 years',
 'Estimate!!Total:!!Female:!!75 to 79 years',
 'Margin of Error!!Total:!!Female:!!75 to 79 years',
 'Estimate!!Total:!!Female:!!80 to 84 years',
 'Margin of Error!!Total:!!Female:!!80 to 84 years',
 'Estimate!!Total:!!Female:!!85 years and over',
 'Margin of Error!!Total:!!Female:!!85 years and over']

In [27]:
#How many people over 65 in the county? 
total_65_count = county_65_plus_pop_official_df[[
    'Estimate!!Total:!!Male:!!65 and 66 years',
 'Estimate!!Total:!!Male:!!67 to 69 years',
 'Estimate!!Total:!!Male:!!70 to 74 years',
 'Estimate!!Total:!!Male:!!75 to 79 years',
 'Estimate!!Total:!!Male:!!80 to 84 years',
 'Estimate!!Total:!!Male:!!85 years and over',
 'Estimate!!Total:!!Female:!!65 and 66 years',
 'Estimate!!Total:!!Female:!!67 to 69 years',
 'Estimate!!Total:!!Female:!!70 to 74 years',
 'Estimate!!Total:!!Female:!!75 to 79 years',
 'Estimate!!Total:!!Female:!!80 to 84 years',
 'Estimate!!Total:!!Female:!!85 years and over']]

county_65_plus_pop_official_df["total_65_count"] = total_65_count.sum(axis=1)

In [60]:
#Percentage of people over 65 across all counties 
((total_65_count.sum().sum())/(county_65_plus_pop_official_df['Estimate!!Total:'].sum()))*100

np.float64(16.65709261553033)

In [62]:
total_65_count.sum().sum()

np.int64(1033741)

In [63]:
county_65_plus_pop_official_df['Estimate!!Total:'].sum()

np.int64(6206011)

In [28]:
county_65_plus_pop_official_df

,Unnamed: 0,Geography,Geographic Area Name,Estimate!!Total:,Estimate!!Total:!!Male:!!65 and 66 years,Margin of Error!!Total:!!Male:!!65 and 66 years,Estimate!!Total:!!Male:!!67 to 69 years,Margin of Error!!Total:!!Male:!!67 to 69 years,Estimate!!Total:!!Male:!!70 to 74 years,Margin of Error!!Total:!!Male:!!70 to 74 years,...,Margin of Error!!Total:!!Female:!!67 to 69 years,Estimate!!Total:!!Female:!!70 to 74 years,Margin of Error!!Total:!!Female:!!70 to 74 years,Estimate!!Total:!!Female:!!75 to 79 years,Margin of Error!!Total:!!Female:!!75 to 79 years,Estimate!!Total:!!Female:!!80 to 84 years,Margin of Error!!Total:!!Female:!!80 to 84 years,Estimate!!Total:!!Female:!!85 years and over,Margin of Error!!Total:!!Female:!!85 years and over,total_65_count
0,1,0500000US24001,"Allegany County, Maryland",67452,836,167,912,142,2069,182,...,148,2415,186,1273,140,1140,193,1251,177,14262
1,2,0500000US24003,"Anne Arundel County, Maryland",598166,5640,546,8299,640,12208,636,...,578,13490,653,9512,556,6634,529,6294,550,94886
2,3,0500000US24005,"Baltimore County, Maryland",850796,8778,661,13129,781,18567,827,...,800,22859,777,15777,772,10899,595,12745,811,154369
3,4,0500000US24009,"Calvert County, Maryland",94313,1255,221,1420,224,1634,235,...,277,2244,234,1835,201,760,165,987,208,15402
4,5,0500000US24011,"Caroline County, Maryland",33669,344,105,527,132,822,150,...,94,909,120,579,133,258,93,543,139,5831
5,6,0500000US24013,"Carroll County, Maryland",175321,1831,281,3022,273,3850,313,...,375,4161,326,3208,319,2172,256,2328,314,31453
6,7,0500000US24015,"Cecil County, Maryland",104960,1369,286,1826,239,2169,225,...,248,2412,337,1772,252,855,214,1082,181,17925
7,8,0500000US24017,"Charles County, Maryland",170527,1683,265,2038,286,2801,317,...,362,3580,426,2247,278,1475,248,1559,252,23350
8,9,0500000US24019,"Dorchester County, Maryland",32754,410,100,513,147,1108,160,...,147,1180,164,808,125,623,143,339,102,7538
9,10,0500000US24021,"Frederick County, Maryland",287048,3138,327,3984,387,5344,369,...,437,5341,378,4586,340,2953,312,2989,348,43882
10,11,0500000US24023,"Garrett County, Maryland",28615,412,95,580,111,973,134,...,141,977,143,716,103,306,79,578,111,6925
11,12,0500000US24025,"Harford County, Maryland",263757,3285,353,4277,437,5483,515,...,462,6130,440,4994,372,3053,315,2820,397,46016
12,13,0500000US24027,"Howard County, Maryland",336328,3612,452,4484,385,6009,443,...,451,7106,443,5725,499,3003,376,3501,495,51275
13,14,0500000US24029,"Kent County, Maryland",19346,207,87,525,120,578,128,...,123,691,127,569,133,335,92,402,104,5305
14,15,0500000US24031,"Montgomery County, Maryland",1065949,11495,723,15368,792,21001,781,...,741,23843,875,18324,817,12553,884,14879,832,181139
15,16,0500000US24033,"Prince George's County, Maryland",959754,9756,827,12061,892,17272,855,...,914,22415,907,13793,674,9011,639,10115,764,143116
16,17,0500000US24035,"Queen Anne's County, Maryland",51825,848,194,987,161,1244,207,...,183,1650,188,1197,231,624,136,603,197,10720
17,18,0500000US24037,"St. Mary's County, Maryland",115126,985,247,1378,240,2381,270,...,276,2021,289,1552,238,839,163,1109,261,16144
18,19,0500000US24039,"Somerset County, Maryland",24822,267,109,512,135,553,122,...,112,726,124,349,104,352,118,300,98,4419
19,20,0500000US24041,"Talbot County, Maryland",37917,531,157,670,132,1383,192,...,187,1699,185,946,190,832,150,1240,235,11210
20,21,0500000US24043,"Washington County, Maryland",155709,2179,297,2434,269,3348,288,...,332,3980,334,3074,315,1795,255,2164,274,28153
21,22,0500000US24045,"Wicomico County, Maryland",104914,1051,319,1817,262,2026,288,...,249,2773,302,1725,270,1256,206,1057,247,17448
22,23,0500000US24047,"Worcester County, Maryland",53700,873,257,1541,267,1649,217,...,232,2062,244,1558,221,1034,183,1132,188,15371
23,24,0500000US24510,"Baltimore city, Maryland",573243,5587,632,7468,613,10142,603,...,657,14024,712,9118,516,5357,441,6358,468,87602

In [29]:
#Percentage of people over 65 in the county?
county_65_plus_pop_official_df["total_65_pct"] = (county_65_plus_pop_official_df["total_65_count"]/county_65_plus_pop_official_df['Estimate!!Total:'])*100

In [30]:
county_65_plus_pop_official_df.sort_values('total_65_pct', ascending = False)

,Unnamed: 0,Geography,Geographic Area Name,Estimate!!Total:,Estimate!!Total:!!Male:!!65 and 66 years,Margin of Error!!Total:!!Male:!!65 and 66 years,Estimate!!Total:!!Male:!!67 to 69 years,Margin of Error!!Total:!!Male:!!67 to 69 years,Estimate!!Total:!!Male:!!70 to 74 years,Margin of Error!!Total:!!Male:!!70 to 74 years,...,Estimate!!Total:!!Female:!!70 to 74 years,Margin of Error!!Total:!!Female:!!70 to 74 years,Estimate!!Total:!!Female:!!75 to 79 years,Margin of Error!!Total:!!Female:!!75 to 79 years,Estimate!!Total:!!Female:!!80 to 84 years,Margin of Error!!Total:!!Female:!!80 to 84 years,Estimate!!Total:!!Female:!!85 years and over,Margin of Error!!Total:!!Female:!!85 years and over,total_65_count,total_65_pct
19,20,0500000US24041,"Talbot County, Maryland",37917,531,157,670,132,1383,192,...,1699,185,946,190,832,150,1240,235,11210,29.564575
22,23,0500000US24047,"Worcester County, Maryland",53700,873,257,1541,267,1649,217,...,2062,244,1558,221,1034,183,1132,188,15371,28.623836
13,14,0500000US24029,"Kent County, Maryland",19346,207,87,525,120,578,128,...,691,127,569,133,335,92,402,104,5305,27.421689
10,11,0500000US24023,"Garrett County, Maryland",28615,412,95,580,111,973,134,...,977,143,716,103,306,79,578,111,6925,24.200594
8,9,0500000US24019,"Dorchester County, Maryland",32754,410,100,513,147,1108,160,...,1180,164,808,125,623,143,339,102,7538,23.013983
0,1,0500000US24001,"Allegany County, Maryland",67452,836,167,912,142,2069,182,...,2415,186,1273,140,1140,193,1251,177,14262,21.143925
16,17,0500000US24035,"Queen Anne's County, Maryland",51825,848,194,987,161,1244,207,...,1650,188,1197,231,624,136,603,197,10720,20.684998
2,3,0500000US24005,"Baltimore County, Maryland",850796,8778,661,13129,781,18567,827,...,22859,777,15777,772,10899,595,12745,811,154369,18.144067
20,21,0500000US24043,"Washington County, Maryland",155709,2179,297,2434,269,3348,288,...,3980,334,3074,315,1795,255,2164,274,28153,18.080522
5,6,0500000US24013,"Carroll County, Maryland",175321,1831,281,3022,273,3850,313,...,4161,326,3208,319,2172,256,2328,314,31453,17.940235
18,19,0500000US24039,"Somerset County, Maryland",24822,267,109,512,135,553,122,...,726,124,349,104,352,118,300,98,4419,17.802756
11,12,0500000US24025,"Harford County, Maryland",263757,3285,353,4277,437,5483,515,...,6130,440,4994,372,3053,315,2820,397,46016,17.446362
4,5,0500000US24011,"Caroline County, Maryland",33669,344,105,527,132,822,150,...,909,120,579,133,258,93,543,139,5831,17.318602
6,7,0500000US24015,"Cecil County, Maryland",104960,1369,286,1826,239,2169,225,...,2412,337,1772,252,855,214,1082,181,17925,17.077934
14,15,0500000US24031,"Montgomery County, Maryland",1065949,11495,723,15368,792,21001,781,...,23843,875,18324,817,12553,884,14879,832,181139,16.993214
21,22,0500000US24045,"Wicomico County, Maryland",104914,1051,319,1817,262,2026,288,...,2773,302,1725,270,1256,206,1057,247,17448,16.630764
3,4,0500000US24009,"Calvert County, Maryland",94313,1255,221,1420,224,1634,235,...,2244,234,1835,201,760,165,987,208,15402,16.330729
1,2,0500000US24003,"Anne Arundel County, Maryland",598166,5640,546,8299,640,12208,636,...,13490,653,9512,556,6634,529,6294,550,94886,15.862821
9,10,0500000US24021,"Frederick County, Maryland",287048,3138,327,3984,387,5344,369,...,5341,378,4586,340,2953,312,2989,348,43882,15.287339
23,24,0500000US24510,"Baltimore city, Maryland",573243,5587,632,7468,613,10142,603,...,14024,712,9118,516,5357,441,6358,468,87602,15.281826
12,13,0500000US24027,"Howard County, Maryland",336328,3612,452,4484,385,6009,443,...,7106,443,5725,499,3003,376,3501,495,51275,15.245534
15,16,0500000US24033,"Prince George's County, Maryland",959754,9756,827,12061,892,17272,855,...,22415,907,13793,674,9011,639,10115,764,143116,14.911738
17,18,0500000US24037,"St. Mary's County, Maryland",115126,985,247,1378,240,2381,270,...,2021,289,1552,238,839,163,1109,261,16144,14.022897
7,8,0500000US24017,"Charles County, Maryland",170527,1683,265,2038,286,2801,317,...,3580,426,2247,278,1475,248,1559,252,23350,13.692846

In [31]:
languages_lep_pct_moe_df_long_wide=languages_lep_pct_moe_df_long_wide.merge(county_65_plus_pop_official_df[['Geographic Area Name', "total_65_count", 'total_65_pct']],
        on='Geographic Area Name',
        how='left')

In [32]:
languages_lep_pct_moe_df_long_wide

,Geographic Area Name,lep_pct_asian_pacific,lep_pct_asian_pacific_65_plus,lep_pct_indo_euro,lep_pct_indo_euro_65_plus,lep_pct_other,lep_pct_other_65_plus,lep_pct_over_5,lep_pct_spanish,lep_pct_spanish_65_plus,total_65_count,total_65_pct
0,"Allegany County, Maryland",52.6,25.0,12.1,19.9,11.9,0.0,1.0,34.8,19.7,14262,21.143925
1,"Anne Arundel County, Maryland",39.9,55.7,24.3,29.6,12.9,17.3,4.5,37.6,28.9,94886,15.862821
2,"Baltimore County, Maryland",39.7,60.3,33.9,51.6,24.4,28.9,5.5,39.8,38.3,154369,18.144067
3,"Baltimore city, Maryland",38.1,66.2,26.9,36.7,31.4,26.0,4.5,44.3,48.8,87602,15.281826
4,"Calvert County, Maryland",37.4,60.3,15.8,40.8,15.7,40.5,1.5,27.6,86.2,15402,16.330729
5,"Caroline County, Maryland",55.6,0.0,18.3,13.3,3.5,100.0,4.4,58.2,23.1,5831,17.318602
6,"Carroll County, Maryland",37.9,58.3,17.9,33.1,20.4,13.2,1.9,32.4,8.8,31453,17.940235
7,"Cecil County, Maryland",39.6,31.3,31.9,49.8,43.2,60.5,2.3,29.0,27.5,17925,17.077934
8,"Charles County, Maryland",27.9,26.7,30.4,38.6,8.1,33.3,3.0,35.9,47.1,23350,13.692846
9,"Dorchester County, Maryland",62.3,76.7,33.2,47.3,0.0,0.0,2.7,46.9,74.7,7538,23.013983
10,"Frederick County, Maryland",34.9,51.7,21.6,36.3,23.1,57.6,5.6,37.1,51.4,43882,15.287339
11,"Garrett County, Maryland",14.2,0.0,2.5,6.1,NaN,NaN,0.4,30.8,11.8,6925,24.200594
12,"Harford County, Maryland",37.7,64.1,17.7,23.9,21.5,59.5,2.5,37.0,28.0,46016,17.446362
13,"Howard County, Maryland",37.0,66.4,22.0,39.2,18.4,34.5,8.8,39.6,43.4,51275,15.245534
14,"Kent County, Maryland",18.4,NaN,25.4,52.0,6.7,NaN,1.4,29.5,8.8,5305,27.421689
15,"Montgomery County, Maryland",41.6,64.4,27.2,39.2,25.8,31.9,15.8,43.4,62.3,181139,16.993214
16,"Prince George's County, Maryland",40.1,51.1,33.2,47.1,22.6,33.3,14.6,57.4,65.3,143116,14.911738
17,"Queen Anne's County, Maryland",44.8,25.2,15.6,21.0,12.2,0.0,2.1,44.2,28.6,10720,20.684998
18,"Somerset County, Maryland",0.0,NaN,17.0,69.2,58.8,100.0,2.8,26.2,0.0,4419,17.802756
19,"St. Mary's County, Maryland",42.2,74.6,38.1,22.7,13.4,0.0,2.6,31.3,37.4,16144,14.022897
20,"Talbot County, Maryland",38.6,93.5,38.5,49.7,60.7,13.3,4.5,47.6,25.9,11210,29.564575
21,"Washington County, Maryland",37.8,22.0,27.6,17.8,10.8,0.0,3.3,41.1,67.2,28153,18.080522
22,"Wicomico County, Maryland",43.7,93.4,60.1,31.5,31.5,0.0,6.5,33.7,2.3,17448,16.630764
23,"Worcester County, Maryland",34.7,100.0,15.4,15.3,51.9,0.0,1.7,35.6,15.8,15371,28.623836

In [33]:
languages_lep_pct_moe_df_long_wide['total_65_pct']=languages_lep_pct_moe_df_long_wide['total_65_pct'].round(2)

In [34]:
languages_lep_pct_moe_df_long_wide

,Geographic Area Name,lep_pct_asian_pacific,lep_pct_asian_pacific_65_plus,lep_pct_indo_euro,lep_pct_indo_euro_65_plus,lep_pct_other,lep_pct_other_65_plus,lep_pct_over_5,lep_pct_spanish,lep_pct_spanish_65_plus,total_65_count,total_65_pct
0,"Allegany County, Maryland",52.6,25.0,12.1,19.9,11.9,0.0,1.0,34.8,19.7,14262,21.14
1,"Anne Arundel County, Maryland",39.9,55.7,24.3,29.6,12.9,17.3,4.5,37.6,28.9,94886,15.86
2,"Baltimore County, Maryland",39.7,60.3,33.9,51.6,24.4,28.9,5.5,39.8,38.3,154369,18.14
3,"Baltimore city, Maryland",38.1,66.2,26.9,36.7,31.4,26.0,4.5,44.3,48.8,87602,15.28
4,"Calvert County, Maryland",37.4,60.3,15.8,40.8,15.7,40.5,1.5,27.6,86.2,15402,16.33
5,"Caroline County, Maryland",55.6,0.0,18.3,13.3,3.5,100.0,4.4,58.2,23.1,5831,17.32
6,"Carroll County, Maryland",37.9,58.3,17.9,33.1,20.4,13.2,1.9,32.4,8.8,31453,17.94
7,"Cecil County, Maryland",39.6,31.3,31.9,49.8,43.2,60.5,2.3,29.0,27.5,17925,17.08
8,"Charles County, Maryland",27.9,26.7,30.4,38.6,8.1,33.3,3.0,35.9,47.1,23350,13.69
9,"Dorchester County, Maryland",62.3,76.7,33.2,47.3,0.0,0.0,2.7,46.9,74.7,7538,23.01
10,"Frederick County, Maryland",34.9,51.7,21.6,36.3,23.1,57.6,5.6,37.1,51.4,43882,15.29
11,"Garrett County, Maryland",14.2,0.0,2.5,6.1,NaN,NaN,0.4,30.8,11.8,6925,24.20
12,"Harford County, Maryland",37.7,64.1,17.7,23.9,21.5,59.5,2.5,37.0,28.0,46016,17.45
13,"Howard County, Maryland",37.0,66.4,22.0,39.2,18.4,34.5,8.8,39.6,43.4,51275,15.25
14,"Kent County, Maryland",18.4,NaN,25.4,52.0,6.7,NaN,1.4,29.5,8.8,5305,27.42
15,"Montgomery County, Maryland",41.6,64.4,27.2,39.2,25.8,31.9,15.8,43.4,62.3,181139,16.99
16,"Prince George's County, Maryland",40.1,51.1,33.2,47.1,22.6,33.3,14.6,57.4,65.3,143116,14.91
17,"Queen Anne's County, Maryland",44.8,25.2,15.6,21.0,12.2,0.0,2.1,44.2,28.6,10720,20.68
18,"Somerset County, Maryland",0.0,NaN,17.0,69.2,58.8,100.0,2.8,26.2,0.0,4419,17.80
19,"St. Mary's County, Maryland",42.2,74.6,38.1,22.7,13.4,0.0,2.6,31.3,37.4,16144,14.02
20,"Talbot County, Maryland",38.6,93.5,38.5,49.7,60.7,13.3,4.5,47.6,25.9,11210,29.56
21,"Washington County, Maryland",37.8,22.0,27.6,17.8,10.8,0.0,3.3,41.1,67.2,28153,18.08
22,"Wicomico County, Maryland",43.7,93.4,60.1,31.5,31.5,0.0,6.5,33.7,2.3,17448,16.63
23,"Worcester County, Maryland",34.7,100.0,15.4,15.3,51.9,0.0,1.7,35.6,15.8,15371,28.62

In [35]:
#total number of LEP speakers in each county, across languages 
#percentage of all LEP speakers in each county, across languages

In [36]:
LEP_counts_total_65_plus = languages_md_county_df[[
                                                   'Estimate!!Speak English  less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish!!65 years old and over"',
                                                   'Estimate!!Speak English  less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other Indo-European languages!!65 years old and over"',
                                                   'Estimate!!Speak English  less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Asian and Pacific Island languages!!65 years old and over"',
                                                   'Estimate!!Speak English  less than very well"!!Percent of specified language speakers!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other languages!!65 years old and over"']]
LEP_counts_total_65_plus=LEP_counts_total_65_plus.astype(int)
languages_md_county_df["LEP_counts_total_65_plus"] = LEP_counts_total_65_plus.sum(axis=1)

In [37]:
language_speakers_counts_total_65_plus = languages_md_county_df[[
'Estimate!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Spanish!!65 years old and over',
'Estimate!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other Indo-European languages!!65 years old and over',
'Estimate!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Asian and Pacific Island languages!!65 years old and over',
'Estimate!!Total!!Population 5 years and over!!SPEAK A LANGUAGE OTHER THAN ENGLISH!!Other languages!!65 years old and over']]

language_speakers_counts_total_65_plus=language_speakers_counts_total_65_plus.astype(int)

languages_md_county_df["language_speakers_counts_total_65_plus"] = (language_speakers_counts_total_65_plus.sum(axis=1))

In [38]:
languages_md_county_df['pct_LEP_language_speakers'] = (languages_md_county_df["LEP_counts_total_65_plus"]/languages_md_county_df["language_speakers_counts_total_65_plus"])*100

In [39]:
languages_lep_pct_moe_df_long_wide=languages_lep_pct_moe_df_long_wide.merge(languages_md_county_df[['Geographic Area Name', 'pct_LEP_language_speakers',"language_speakers_counts_total_65_plus", 'LEP_counts_total_65_plus']],
        on='Geographic Area Name',
        how='left').round(2)

In [45]:
languages_lep_pct_moe_df_long_wide['pct_language_speakers'] = (languages_lep_pct_moe_df_long_wide["language_speakers_counts_total_65_plus"]/languages_lep_pct_moe_df_long_wide["total_65_count"])*100

SyntaxError: invalid decimal literal (4124654191.py, line 1)

In [47]:
languages_lep_pct_moe_df_long_wide['pct_language_speakers']=languages_lep_pct_moe_df_long_wide['pct_language_speakers'].round(2)

In [49]:
languages_lep_pct_moe_df_long_wide

,Geographic Area Name,lep_pct_asian_pacific,lep_pct_asian_pacific_65_plus,lep_pct_indo_euro,lep_pct_indo_euro_65_plus,lep_pct_other,lep_pct_other_65_plus,lep_pct_over_5,lep_pct_spanish,lep_pct_spanish_65_plus,total_65_count,total_65_pct,pct_LEP_language_speakers,language_speakers_counts_total_65_plus,LEP_counts_total_65_plus,pct_language_speakers
0,"Allegany County, Maryland",52.6,25.0,12.1,19.9,11.9,0.0,1.0,34.8,19.7,14262,21.14,19.78,369,73,2.59
1,"Anne Arundel County, Maryland",39.9,55.7,24.3,29.6,12.9,17.3,4.5,37.6,28.9,94886,15.86,37.00,8897,3292,9.38
2,"Baltimore County, Maryland",39.7,60.3,33.9,51.6,24.4,28.9,5.5,39.8,38.3,154369,18.14,48.55,16067,7801,10.41
3,"Baltimore city, Maryland",38.1,66.2,26.9,36.7,31.4,26.0,4.5,44.3,48.8,87602,15.28,45.42,6392,2903,7.30
4,"Calvert County, Maryland",37.4,60.3,15.8,40.8,15.7,40.5,1.5,27.6,86.2,15402,16.33,57.03,640,365,4.16
5,"Caroline County, Maryland",55.6,0.0,18.3,13.3,3.5,100.0,4.4,58.2,23.1,5831,17.32,20.54,185,38,3.17
6,"Carroll County, Maryland",37.9,58.3,17.9,33.1,20.4,13.2,1.9,32.4,8.8,31453,17.94,31.36,1470,461,4.67
7,"Cecil County, Maryland",39.6,31.3,31.9,49.8,43.2,60.5,2.3,29.0,27.5,17925,17.08,38.15,692,264,3.86
8,"Charles County, Maryland",27.9,26.7,30.4,38.6,8.1,33.3,3.0,35.9,47.1,23350,13.69,36.40,1709,622,7.32
9,"Dorchester County, Maryland",62.3,76.7,33.2,47.3,0.0,0.0,2.7,46.9,74.7,7538,23.01,59.18,365,216,4.84
10,"Frederick County, Maryland",34.9,51.7,21.6,36.3,23.1,57.6,5.6,37.1,51.4,43882,15.29,47.39,4385,2078,9.99
11,"Garrett County, Maryland",14.2,0.0,2.5,6.1,NaN,NaN,0.4,30.8,11.8,6925,24.20,6.49,154,10,2.22
12,"Harford County, Maryland",37.7,64.1,17.7,23.9,21.5,59.5,2.5,37.0,28.0,46016,17.45,35.42,3340,1183,7.26
13,"Howard County, Maryland",37.0,66.4,22.0,39.2,18.4,34.5,8.8,39.6,43.4,51275,15.25,52.24,11342,5925,22.12
14,"Kent County, Maryland",18.4,NaN,25.4,52.0,6.7,NaN,1.4,29.5,8.8,5305,27.42,27.12,59,16,1.11
15,"Montgomery County, Maryland",41.6,64.4,27.2,39.2,25.8,31.9,15.8,43.4,62.3,181139,16.99,53.40,62672,33468,34.60
16,"Prince George's County, Maryland",40.1,51.1,33.2,47.1,22.6,33.3,14.6,57.4,65.3,143116,14.91,51.71,24269,12549,16.96
17,"Queen Anne's County, Maryland",44.8,25.2,15.6,21.0,12.2,0.0,2.1,44.2,28.6,10720,20.68,23.26,417,97,3.89
18,"Somerset County, Maryland",0.0,NaN,17.0,69.2,58.8,100.0,2.8,26.2,0.0,4419,17.80,60.55,109,66,2.47
19,"St. Mary's County, Maryland",42.2,74.6,38.1,22.7,13.4,0.0,2.6,31.3,37.4,16144,14.02,46.70,743,347,4.60
20,"Talbot County, Maryland",38.6,93.5,38.5,49.7,60.7,13.3,4.5,47.6,25.9,11210,29.56,47.68,518,247,4.62
21,"Washington County, Maryland",37.8,22.0,27.6,17.8,10.8,0.0,3.3,41.1,67.2,28153,18.08,37.49,1419,532,5.04
22,"Wicomico County, Maryland",43.7,93.4,60.1,31.5,31.5,0.0,6.5,33.7,2.3,17448,16.63,32.96,1168,385,6.69
23,"Worcester County, Maryland",34.7,100.0,15.4,15.3,51.9,0.0,1.7,35.6,15.8,15371,28.62,15.51,619,96,4.03

In [50]:
languages_lep_pct_moe_df_long_wide.to_csv("languages_lep_pct_moe_df_long_wide.csv")

In [55]:
#state averages
languages_lep_pct_moe_df_long_wide['pct_language_speakers'].median()

np.float64(4.755)

In [56]:
languages_lep_pct_moe_df_long_wide['pct_LEP_language_speakers'].median()

np.float64(37.82)

In [57]:
languages_lep_pct_moe_df_long_wide['total_65_pct'].median()

np.float64(17.384999999999998)