In [1]:
import pandas as pd

In [2]:
lang_specific_state_df = pd.read_csv("specific-lang-1year-state-ACSDT1Y2024.B16001-2026-07-25T141509.csv")

In [3]:
lang_specific_state_df

,Label (Grouping),Maryland!!Estimate,Maryland!!Margin of Error
0,Total:,"5,912,247","±2,514"
1,Speak only English,"4,624,493","±26,586"
2,Spanish:,"597,081","±13,591"
3,"Speak English ""very well""","317,783","±13,292"
4,"Speak English less than ""very well""","279,298","±14,065"
...,...,...,...
123,"Speak English ""very well""",614,±561
124,"Speak English less than ""very well""",119,±194
125,Other and unspecified languages:,"17,228","±4,523"
126,"Speak English ""very well""","12,110","±3,383"
127,"Speak English less than ""very well""","5,118","±2,541"

In [4]:
pd.set_option('display.max_rows', None)
lang_specific_state_df

#create bart graph where each language is its own color gradient
#rename columns: addlanguage in front of other metrics

,Label (Grouping),Maryland!!Estimate,Maryland!!Margin of Error
0,Total:,"5,912,247","±2,514"
1,Speak only English,"4,624,493","±26,586"
2,Spanish:,"597,081","±13,591"
3,"Speak English ""very well""","317,783","±13,292"
4,"Speak English less than ""very well""","279,298","±14,065"
5,French (incl. Cajun):,"59,893","±8,106"
6,"Speak English ""very well""","44,516","±6,604"
7,"Speak English less than ""very well""","15,377","±3,144"
8,Haitian:,"16,844","±4,691"
9,"Speak English ""very well""","12,166","±3,945"
10,"Speak English less than ""very well""","4,678","±1,779"
11,Italian:,"7,754","±1,987"
12,"Speak English ""very well""","6,036","±1,689"
13,"Speak English less than ""very well""","1,718",±802
14,Portuguese:,"16,069","±3,936"
15,"Speak English ""very well""","10,022","±2,541"
16,"Speak English less than ""very well""","6,047","±2,293"
17,German:,"15,592","±3,484"
18,"Speak English ""very well""","13,900","±3,102"
19,"Speak English less than ""very well""","1,692",±860
20,"Yiddish, Pennsylvania Dutch or other West ...","4,503","±1,437"
21,"Speak English ""very well""","3,765","±1,281"
22,"Speak English less than ""very well""",738,±498
23,Greek:,"6,089","±1,764"
24,"Speak English ""very well""","4,988","±1,600"
25,"Speak English less than ""very well""","1,101",±503
26,Russian:,"19,214","±4,390"
27,"Speak English ""very well""","12,137","±3,048"
28,"Speak English less than ""very well""","7,077","±2,103"
29,Polish:,"3,795","±1,210"
30,"Speak English ""very well""","2,718","±1,015"
31,"Speak English less than ""very well""","1,077",±599
32,Serbo-Croatian:,"2,049","±1,391"
33,"Speak English ""very well""","1,044",±663
34,"Speak English less than ""very well""","1,005",±944
35,Ukrainian or other Slavic languages:,"8,531","±2,743"
36,"Speak English ""very well""","6,148","±2,059"
37,"Speak English less than ""very well""","2,383","±1,296"
38,Armenian:,"2,174","±1,690"
39,"Speak English ""very well""","1,646","±1,162"
40,"Speak English less than ""very well""",528,±589
41,"Persian (incl. Farsi, Dari):","16,666","±4,074"
42,"Speak English ""very well""","10,665","±3,215"
43,"Speak English less than ""very well""","6,001","±2,031"
44,Gujarati:,"10,369","±3,709"
45,"Speak English ""very well""","8,292","±3,329"
46,"Speak English less than ""very well""","2,077",±948
47,Hindi:,"22,610","±3,688"
48,"Speak English ""very well""","18,613","±3,433"
49,"Speak English less than ""very well""","3,997","±1,345"
50,Urdu:,"19,812","±5,088"
51,"Speak English ""very well""","12,274","±2,751"
52,"Speak English less than ""very well""","7,538","±3,064"
53,Punjabi:,"5,965","±2,333"
54,"Speak English ""very well""","4,700","±2,020"
55,"Speak English less than ""very well""","1,265",±673
56,Bengali:,"16,169","±4,775"
57,"Speak English ""very well""","10,877","±3,300"
58,"Speak English less than ""very well""","5,292","±2,190"
59,"Nepali, Marathi, or other Indic languages:","12,872","±3,203"
60,"Speak English ""very well""","9,623","±2,537"
61,"Speak English less than ""very well""","3,249","±1,559"
62,Other Indo-European languages:,"12,707","±3,728"
63,"Speak English ""very well""","8,257","±2,526"
64,"Speak English less than ""very well""","4,450","±2,005"
65,Telugu:,"11,834","±4,745"
66,"Speak English ""very well""","10,532","±4,150"
67,"Speak English less than ""very well""","1,302",±889
68,Tamil:,"9,049","±2,456"
69,"Speak English ""very well""","7,887","±2,310"
70,"Speak English less than ""very well""","1,162",±596
71,"Malayalam, Kannada, or other Dravidian lan...","3,946","±1,507"
72,"Speak English ""very well""","3,258","±1,203"
73,"Speak English less than ""very well""",688,±487
74,"Chinese (incl. Mandarin, Cantonese):","74,664","±7,547"
75,"Speak English ""very well""","39,071","±4,449"
76,"Speak English less than ""very well""","35,593","±5,192"
77,Japanese:,"7,103","±1,667"
78,"Speak English ""very well""","4,102","±1,155"
79,"Speak English less than ""very well""","3,001","±1,079"
80,Korean:,"35,309","±4,895"
81,"Speak English ""very well""","19,433","±3,205"
82,"Speak English less than ""very well""","15,876","±2,921"
83,Hmong:,194,±313
84,"Speak English ""very well""",194,±313
85,"Speak English less than ""very well""",0,±228
86,Vietnamese:,"20,780","±3,991"
87,"Speak English ""very well""","10,582","±2,422"
88,"Speak English less than ""very well""","10,198","±2,586"
89,Khmer:,"1,802",±864
90,"Speak English ""very well""",772,±538
91,"Speak English less than ""very well""","1,030",±570
92,"Thai, Lao, or other Tai-Kadai languages:","3,879","±1,099"
93,"Speak English ""very well""","2,424",±808
94,"Speak English less than ""very well""","1,455",±529
95,Other languages of Asia:,"12,096","±3,710"
96,"Speak English ""very well""","7,463","±2,527"
97,"Speak English less than ""very well""","4,633","±1,605"
98,Tagalog (incl. Filipino):,"44,915","±6,885"
99,"Speak English ""very well""","31,227","±5,666"
100,"Speak English less than ""very well""","13,688","±3,173"
101,"Ilocano, Samoan, Hawaiian, or other Austro...","8,585","±2,359"
102,"Speak English ""very well""","5,168","±1,778"
103,"Speak English less than ""very well""","3,417","±1,258"
104,Arabic:,"19,491","±4,360"
105,"Speak English ""very well""","13,673","±3,606"
106,"Speak English less than ""very well""","5,818","±2,023"
107,Hebrew:,"6,160","±1,789"
108,"Speak English ""very well""","5,830","±1,795"
109,"Speak English less than ""very well""",330,±270
110,"Amharic, Somali, or other Afro-Asiatic lan...","44,299","±6,897"
111,"Speak English ""very well""","31,339","±5,848"
112,"Speak English less than ""very well""","12,960","±2,553"
113,"Yoruba, Twi, Igbo, or other languages of W...","75,279","±9,886"
114,"Speak English ""very well""","63,495","±8,676"
115,"Speak English less than ""very well""","11,784","±3,125"
116,"Swahili or other languages of Central, Eas...","13,650","±4,695"
117,"Speak English ""very well""","10,620","±3,651"
118,"Speak English less than ""very well""","3,030","±1,639"
119,Navajo:,0,±228
120,"Speak English ""very well""",0,±228
121,"Speak English less than ""very well""",0,±228
122,Other Native languages of North America:,733,±640
123,"Speak English ""very well""",614,±561
124,"Speak English less than ""very well""",119,±194
125,Other and unspecified languages:,"17,228","±4,523"
126,"Speak English ""very well""","12,110","±3,383"
127,"Speak English less than ""very well""","5,118","±2,541"

In [5]:
# identify language rows
lang_specific_state_df["language"] = lang_specific_state_df["Label (Grouping)"].where(
    lang_specific_state_df["Label (Grouping)"].str.endswith(":")
)

In [6]:
# carry language down
lang_specific_state_df["language"] = lang_specific_state_df["language"].ffill(limit=2).str.strip(":").str.strip()

In [7]:
lang_specific_state_df_copy=lang_specific_state_df.copy()

In [8]:
lang_specific_state_df_copy=lang_specific_state_df_copy.rename(columns=
                                                                     {'Label (Grouping)': 'proficiency',
                                                                     'Maryland!!Estimate': 'estimated_speakers_count',
                                                                     'Maryland!!Margin of Error': 'moe'})

In [9]:
lang_specific_state_df_with_total=lang_specific_state_df_copy.copy()

In [10]:
lang_specific_state_df_copy.at[1,'language']='English'

In [11]:
lang_specific_state_df_copy=lang_specific_state_df_copy.drop(0)

In [12]:
lang_specific_state_df_copy['estimated_speakers_count']=lang_specific_state_df_copy['estimated_speakers_count'].str.replace(",","")

In [13]:
lang_specific_state_df_copy['moe']=lang_specific_state_df_copy['moe'].str.replace(",","")

In [14]:
lang_specific_state_df_copy['proficiency'] = lang_specific_state_df_copy['proficiency'].str.strip(":").str.strip()

In [15]:
lang_specific_state_df_copy.head()

,proficiency,estimated_speakers_count,moe,language
1,Speak only English,4624493,±26586,English
2,Spanish,597081,±13591,Spanish
3,"Speak English ""very well""",317783,±13292,Spanish
4,"Speak English less than ""very well""",279298,±14065,Spanish
5,French (incl. Cajun),59893,±8106,French (incl. Cajun)

In [16]:
lang_specific_state_df_copy['estimated_speakers_count']=lang_specific_state_df_copy['estimated_speakers_count'].astype(int)

In [17]:
# lang_specific_state_df_with_total
# 5912247

In [18]:
lang_specific_state_df_copy['pct_of_total_pop'] = ((lang_specific_state_df_copy['estimated_speakers_count']/5912247)*100).round(2)

In [19]:
#Question 1: What share of Maryland's population speaks each language? 
lang_specific_state_df_copy

,proficiency,estimated_speakers_count,moe,language,pct_of_total_pop
1,Speak only English,4624493,±26586,English,78.22
2,Spanish,597081,±13591,Spanish,10.10
3,"Speak English ""very well""",317783,±13292,Spanish,5.37
4,"Speak English less than ""very well""",279298,±14065,Spanish,4.72
5,French (incl. Cajun),59893,±8106,French (incl. Cajun),1.01
6,"Speak English ""very well""",44516,±6604,French (incl. Cajun),0.75
7,"Speak English less than ""very well""",15377,±3144,French (incl. Cajun),0.26
8,Haitian,16844,±4691,Haitian,0.28
9,"Speak English ""very well""",12166,±3945,Haitian,0.21
10,"Speak English less than ""very well""",4678,±1779,Haitian,0.08
11,Italian,7754,±1987,Italian,0.13
12,"Speak English ""very well""",6036,±1689,Italian,0.10
13,"Speak English less than ""very well""",1718,±802,Italian,0.03
14,Portuguese,16069,±3936,Portuguese,0.27
15,"Speak English ""very well""",10022,±2541,Portuguese,0.17
16,"Speak English less than ""very well""",6047,±2293,Portuguese,0.10
17,German,15592,±3484,German,0.26
18,"Speak English ""very well""",13900,±3102,German,0.24
19,"Speak English less than ""very well""",1692,±860,German,0.03
20,"Yiddish, Pennsylvania Dutch or other West Germ...",4503,±1437,"Yiddish, Pennsylvania Dutch or other West Germ...",0.08
21,"Speak English ""very well""",3765,±1281,"Yiddish, Pennsylvania Dutch or other West Germ...",0.06
22,"Speak English less than ""very well""",738,±498,"Yiddish, Pennsylvania Dutch or other West Germ...",0.01
23,Greek,6089,±1764,Greek,0.10
24,"Speak English ""very well""",4988,±1600,Greek,0.08
25,"Speak English less than ""very well""",1101,±503,Greek,0.02
26,Russian,19214,±4390,Russian,0.32
27,"Speak English ""very well""",12137,±3048,Russian,0.21
28,"Speak English less than ""very well""",7077,±2103,Russian,0.12
29,Polish,3795,±1210,Polish,0.06
30,"Speak English ""very well""",2718,±1015,Polish,0.05
31,"Speak English less than ""very well""",1077,±599,Polish,0.02
32,Serbo-Croatian,2049,±1391,Serbo-Croatian,0.03
33,"Speak English ""very well""",1044,±663,Serbo-Croatian,0.02
34,"Speak English less than ""very well""",1005,±944,Serbo-Croatian,0.02
35,Ukrainian or other Slavic languages,8531,±2743,Ukrainian or other Slavic languages,0.14
36,"Speak English ""very well""",6148,±2059,Ukrainian or other Slavic languages,0.10
37,"Speak English less than ""very well""",2383,±1296,Ukrainian or other Slavic languages,0.04
38,Armenian,2174,±1690,Armenian,0.04
39,"Speak English ""very well""",1646,±1162,Armenian,0.03
40,"Speak English less than ""very well""",528,±589,Armenian,0.01
41,"Persian (incl. Farsi, Dari)",16666,±4074,"Persian (incl. Farsi, Dari)",0.28
42,"Speak English ""very well""",10665,±3215,"Persian (incl. Farsi, Dari)",0.18
43,"Speak English less than ""very well""",6001,±2031,"Persian (incl. Farsi, Dari)",0.10
44,Gujarati,10369,±3709,Gujarati,0.18
45,"Speak English ""very well""",8292,±3329,Gujarati,0.14
46,"Speak English less than ""very well""",2077,±948,Gujarati,0.04
47,Hindi,22610,±3688,Hindi,0.38
48,"Speak English ""very well""",18613,±3433,Hindi,0.31
49,"Speak English less than ""very well""",3997,±1345,Hindi,0.07
50,Urdu,19812,±5088,Urdu,0.34
51,"Speak English ""very well""",12274,±2751,Urdu,0.21
52,"Speak English less than ""very well""",7538,±3064,Urdu,0.13
53,Punjabi,5965,±2333,Punjabi,0.10
54,"Speak English ""very well""",4700,±2020,Punjabi,0.08
55,"Speak English less than ""very well""",1265,±673,Punjabi,0.02
56,Bengali,16169,±4775,Bengali,0.27
57,"Speak English ""very well""",10877,±3300,Bengali,0.18
58,"Speak English less than ""very well""",5292,±2190,Bengali,0.09
59,"Nepali, Marathi, or other Indic languages",12872,±3203,"Nepali, Marathi, or other Indic languages",0.22
60,"Speak English ""very well""",9623,±2537,"Nepali, Marathi, or other Indic languages",0.16
61,"Speak English less than ""very well""",3249,±1559,"Nepali, Marathi, or other Indic languages",0.05
62,Other Indo-European languages,12707,±3728,Other Indo-European languages,0.21
63,"Speak English ""very well""",8257,±2526,Other Indo-European languages,0.14
64,"Speak English less than ""very well""",4450,±2005,Other Indo-European languages,0.08
65,Telugu,11834,±4745,Telugu,0.20
66,"Speak English ""very well""",10532,±4150,Telugu,0.18
67,"Speak English less than ""very well""",1302,±889,Telugu,0.02
68,Tamil,9049,±2456,Tamil,0.15
69,"Speak English ""very well""",7887,±2310,Tamil,0.13
70,"Speak English less than ""very well""",1162,±596,Tamil,0.02
71,"Malayalam, Kannada, or other Dravidian languages",3946,±1507,"Malayalam, Kannada, or other Dravidian languages",0.07
72,"Speak English ""very well""",3258,±1203,"Malayalam, Kannada, or other Dravidian languages",0.06
73,"Speak English less than ""very well""",688,±487,"Malayalam, Kannada, or other Dravidian languages",0.01
74,"Chinese (incl. Mandarin, Cantonese)",74664,±7547,"Chinese (incl. Mandarin, Cantonese)",1.26
75,"Speak English ""very well""",39071,±4449,"Chinese (incl. Mandarin, Cantonese)",0.66
76,"Speak English less than ""very well""",35593,±5192,"Chinese (incl. Mandarin, Cantonese)",0.60
77,Japanese,7103,±1667,Japanese,0.12
78,"Speak English ""very well""",4102,±1155,Japanese,0.07
79,"Speak English less than ""very well""",3001,±1079,Japanese,0.05
80,Korean,35309,±4895,Korean,0.60
81,"Speak English ""very well""",19433,±3205,Korean,0.33
82,"Speak English less than ""very well""",15876,±2921,Korean,0.27
83,Hmong,194,±313,Hmong,0.00
84,"Speak English ""very well""",194,±313,Hmong,0.00
85,"Speak English less than ""very well""",0,±228,Hmong,0.00
86,Vietnamese,20780,±3991,Vietnamese,0.35
87,"Speak English ""very well""",10582,±2422,Vietnamese,0.18
88,"Speak English less than ""very well""",10198,±2586,Vietnamese,0.17
89,Khmer,1802,±864,Khmer,0.03
90,"Speak English ""very well""",772,±538,Khmer,0.01
91,"Speak English less than ""very well""",1030,±570,Khmer,0.02
92,"Thai, Lao, or other Tai-Kadai languages",3879,±1099,"Thai, Lao, or other Tai-Kadai languages",0.07
93,"Speak English ""very well""",2424,±808,"Thai, Lao, or other Tai-Kadai languages",0.04
94,"Speak English less than ""very well""",1455,±529,"Thai, Lao, or other Tai-Kadai languages",0.02
95,Other languages of Asia,12096,±3710,Other languages of Asia,0.20
96,"Speak English ""very well""",7463,±2527,Other languages of Asia,0.13
97,"Speak English less than ""very well""",4633,±1605,Other languages of Asia,0.08
98,Tagalog (incl. Filipino),44915,±6885,Tagalog (incl. Filipino),0.76
99,"Speak English ""very well""",31227,±5666,Tagalog (incl. Filipino),0.53
100,"Speak English less than ""very well""",13688,±3173,Tagalog (incl. Filipino),0.23
101,"Ilocano, Samoan, Hawaiian, or other Austronesi...",8585,±2359,"Ilocano, Samoan, Hawaiian, or other Austronesi...",0.15
102,"Speak English ""very well""",5168,±1778,"Ilocano, Samoan, Hawaiian, or other Austronesi...",0.09
103,"Speak English less than ""very well""",3417,±1258,"Ilocano, Samoan, Hawaiian, or other Austronesi...",0.06
104,Arabic,19491,±4360,Arabic,0.33
105,"Speak English ""very well""",13673,±3606,Arabic,0.23
106,"Speak English less than ""very well""",5818,±2023,Arabic,0.10
107,Hebrew,6160,±1789,Hebrew,0.10
108,"Speak English ""very well""",5830,±1795,Hebrew,0.10
109,"Speak English less than ""very well""",330,±270,Hebrew,0.01
110,"Amharic, Somali, or other Afro-Asiatic languages",44299,±6897,"Amharic, Somali, or other Afro-Asiatic languages",0.75
111,"Speak English ""very well""",31339,±5848,"Amharic, Somali, or other Afro-Asiatic languages",0.53
112,"Speak English less than ""very well""",12960,±2553,"Amharic, Somali, or other Afro-Asiatic languages",0.22
113,"Yoruba, Twi, Igbo, or other languages of Weste...",75279,±9886,"Yoruba, Twi, Igbo, or other languages of Weste...",1.27
114,"Speak English ""very well""",63495,±8676,"Yoruba, Twi, Igbo, or other languages of Weste...",1.07
115,"Speak English less than ""very well""",11784,±3125,"Yoruba, Twi, Igbo, or other languages of Weste...",0.20
116,"Swahili or other languages of Central, Eastern...",13650,±4695,"Swahili or other languages of Central, Eastern...",0.23
117,"Speak English ""very well""",10620,±3651,"Swahili or other languages of Central, Eastern...",0.18
118,"Speak English less than ""very well""",3030,±1639,"Swahili or other languages of Central, Eastern...",0.05
119,Navajo,0,±228,Navajo,0.00
120,"Speak English ""very well""",0,±228,Navajo,0.00
121,"Speak English less than ""very well""",0,±228,Navajo,0.00
122,Other Native languages of North America,733,±640,Other Native languages of North America,0.01
123,"Speak English ""very well""",614,±561,Other Native languages of North America,0.01
124,"Speak English less than ""very well""",119,±194,Other Native languages of North America,0.00
125,Other and unspecified languages,17228,±4523,Other and unspecified languages,0.29
126,"Speak English ""very well""",12110,±3383,Other and unspecified languages,0.20
127,"Speak English less than ""very well""",5118,±2541,Other and unspecified languages,0.09

In [20]:
#Question 2: Within each language, what percentage speaks English very well vs less than very well?

In [21]:
lang_specific_proficiency_state_df = lang_specific_state_df_copy.copy()

In [22]:
lang_specific_proficiency_state_df.head()

,proficiency,estimated_speakers_count,moe,language,pct_of_total_pop
1,Speak only English,4624493,±26586,English,78.22
2,Spanish,597081,±13591,Spanish,10.10
3,"Speak English ""very well""",317783,±13292,Spanish,5.37
4,"Speak English less than ""very well""",279298,±14065,Spanish,4.72
5,French (incl. Cajun),59893,±8106,French (incl. Cajun),1.01

In [23]:
lang_specific_proficiency_state_df['speaker_count_by_language'] = (lang_specific_proficiency_state_df['estimated_speakers_count']
    .where(~lang_specific_proficiency_state_df['proficiency'].str.contains("Speak English", na=False))).ffill(limit=2)

In [24]:
lang_specific_proficiency_state_df.head()

,proficiency,estimated_speakers_count,moe,language,pct_of_total_pop,speaker_count_by_language
1,Speak only English,4624493,±26586,English,78.22,4624493.0
2,Spanish,597081,±13591,Spanish,10.10,597081.0
3,"Speak English ""very well""",317783,±13292,Spanish,5.37,597081.0
4,"Speak English less than ""very well""",279298,±14065,Spanish,4.72,597081.0
5,French (incl. Cajun),59893,±8106,French (incl. Cajun),1.01,59893.0

In [25]:
lang_specific_proficiency_state_df['proficiency_pct_by_language'] = ((lang_specific_proficiency_state_df['estimated_speakers_count']/lang_specific_proficiency_state_df['speaker_count_by_language'])*100).round(2)
# lang_specific_proficiency_state_df['proficiency_pct_by_language'] = (lang_specific_proficiency_state_df['proficiency_pct_by_language']
#     .where(lang_specific_proficiency_state_df['proficiency_pct_by_language'] != 100.00))

In [26]:
lang_specific_proficiency_state_df['proficiency'] = (lang_specific_proficiency_state_df['proficiency'].where(lang_specific_proficiency_state_df['proficiency'].str.contains("Speak English|Speak only English", na=False))
)

In [27]:
lang_specific_proficiency_state_df

,proficiency,estimated_speakers_count,moe,language,pct_of_total_pop,speaker_count_by_language,proficiency_pct_by_language
1,Speak only English,4624493,±26586,English,78.22,4624493.0,100.00
2,NaN,597081,±13591,Spanish,10.10,597081.0,100.00
3,"Speak English ""very well""",317783,±13292,Spanish,5.37,597081.0,53.22
4,"Speak English less than ""very well""",279298,±14065,Spanish,4.72,597081.0,46.78
5,NaN,59893,±8106,French (incl. Cajun),1.01,59893.0,100.00
6,"Speak English ""very well""",44516,±6604,French (incl. Cajun),0.75,59893.0,74.33
7,"Speak English less than ""very well""",15377,±3144,French (incl. Cajun),0.26,59893.0,25.67
8,NaN,16844,±4691,Haitian,0.28,16844.0,100.00
9,"Speak English ""very well""",12166,±3945,Haitian,0.21,16844.0,72.23
10,"Speak English less than ""very well""",4678,±1779,Haitian,0.08,16844.0,27.77
11,NaN,7754,±1987,Italian,0.13,7754.0,100.00
12,"Speak English ""very well""",6036,±1689,Italian,0.10,7754.0,77.84
13,"Speak English less than ""very well""",1718,±802,Italian,0.03,7754.0,22.16
14,NaN,16069,±3936,Portuguese,0.27,16069.0,100.00
15,"Speak English ""very well""",10022,±2541,Portuguese,0.17,16069.0,62.37
16,"Speak English less than ""very well""",6047,±2293,Portuguese,0.10,16069.0,37.63
17,NaN,15592,±3484,German,0.26,15592.0,100.00
18,"Speak English ""very well""",13900,±3102,German,0.24,15592.0,89.15
19,"Speak English less than ""very well""",1692,±860,German,0.03,15592.0,10.85
20,NaN,4503,±1437,"Yiddish, Pennsylvania Dutch or other West Germ...",0.08,4503.0,100.00
21,"Speak English ""very well""",3765,±1281,"Yiddish, Pennsylvania Dutch or other West Germ...",0.06,4503.0,83.61
22,"Speak English less than ""very well""",738,±498,"Yiddish, Pennsylvania Dutch or other West Germ...",0.01,4503.0,16.39
23,NaN,6089,±1764,Greek,0.10,6089.0,100.00
24,"Speak English ""very well""",4988,±1600,Greek,0.08,6089.0,81.92
25,"Speak English less than ""very well""",1101,±503,Greek,0.02,6089.0,18.08
26,NaN,19214,±4390,Russian,0.32,19214.0,100.00
27,"Speak English ""very well""",12137,±3048,Russian,0.21,19214.0,63.17
28,"Speak English less than ""very well""",7077,±2103,Russian,0.12,19214.0,36.83
29,NaN,3795,±1210,Polish,0.06,3795.0,100.00
30,"Speak English ""very well""",2718,±1015,Polish,0.05,3795.0,71.62
31,"Speak English less than ""very well""",1077,±599,Polish,0.02,3795.0,28.38
32,NaN,2049,±1391,Serbo-Croatian,0.03,2049.0,100.00
33,"Speak English ""very well""",1044,±663,Serbo-Croatian,0.02,2049.0,50.95
34,"Speak English less than ""very well""",1005,±944,Serbo-Croatian,0.02,2049.0,49.05
35,NaN,8531,±2743,Ukrainian or other Slavic languages,0.14,8531.0,100.00
36,"Speak English ""very well""",6148,±2059,Ukrainian or other Slavic languages,0.10,8531.0,72.07
37,"Speak English less than ""very well""",2383,±1296,Ukrainian or other Slavic languages,0.04,8531.0,27.93
38,NaN,2174,±1690,Armenian,0.04,2174.0,100.00
39,"Speak English ""very well""",1646,±1162,Armenian,0.03,2174.0,75.71
40,"Speak English less than ""very well""",528,±589,Armenian,0.01,2174.0,24.29
41,NaN,16666,±4074,"Persian (incl. Farsi, Dari)",0.28,16666.0,100.00
42,"Speak English ""very well""",10665,±3215,"Persian (incl. Farsi, Dari)",0.18,16666.0,63.99
43,"Speak English less than ""very well""",6001,±2031,"Persian (incl. Farsi, Dari)",0.10,16666.0,36.01
44,NaN,10369,±3709,Gujarati,0.18,10369.0,100.00
45,"Speak English ""very well""",8292,±3329,Gujarati,0.14,10369.0,79.97
46,"Speak English less than ""very well""",2077,±948,Gujarati,0.04,10369.0,20.03
47,NaN,22610,±3688,Hindi,0.38,22610.0,100.00
48,"Speak English ""very well""",18613,±3433,Hindi,0.31,22610.0,82.32
49,"Speak English less than ""very well""",3997,±1345,Hindi,0.07,22610.0,17.68
50,NaN,19812,±5088,Urdu,0.34,19812.0,100.00
51,"Speak English ""very well""",12274,±2751,Urdu,0.21,19812.0,61.95
52,"Speak English less than ""very well""",7538,±3064,Urdu,0.13,19812.0,38.05
53,NaN,5965,±2333,Punjabi,0.10,5965.0,100.00
54,"Speak English ""very well""",4700,±2020,Punjabi,0.08,5965.0,78.79
55,"Speak English less than ""very well""",1265,±673,Punjabi,0.02,5965.0,21.21
56,NaN,16169,±4775,Bengali,0.27,16169.0,100.00
57,"Speak English ""very well""",10877,±3300,Bengali,0.18,16169.0,67.27
58,"Speak English less than ""very well""",5292,±2190,Bengali,0.09,16169.0,32.73
59,NaN,12872,±3203,"Nepali, Marathi, or other Indic languages",0.22,12872.0,100.00
60,"Speak English ""very well""",9623,±2537,"Nepali, Marathi, or other Indic languages",0.16,12872.0,74.76
61,"Speak English less than ""very well""",3249,±1559,"Nepali, Marathi, or other Indic languages",0.05,12872.0,25.24
62,NaN,12707,±3728,Other Indo-European languages,0.21,12707.0,100.00
63,"Speak English ""very well""",8257,±2526,Other Indo-European languages,0.14,12707.0,64.98
64,"Speak English less than ""very well""",4450,±2005,Other Indo-European languages,0.08,12707.0,35.02
65,NaN,11834,±4745,Telugu,0.20,11834.0,100.00
66,"Speak English ""very well""",10532,±4150,Telugu,0.18,11834.0,89.00
67,"Speak English less than ""very well""",1302,±889,Telugu,0.02,11834.0,11.00
68,NaN,9049,±2456,Tamil,0.15,9049.0,100.00
69,"Speak English ""very well""",7887,±2310,Tamil,0.13,9049.0,87.16
70,"Speak English less than ""very well""",1162,±596,Tamil,0.02,9049.0,12.84
71,NaN,3946,±1507,"Malayalam, Kannada, or other Dravidian languages",0.07,3946.0,100.00
72,"Speak English ""very well""",3258,±1203,"Malayalam, Kannada, or other Dravidian languages",0.06,3946.0,82.56
73,"Speak English less than ""very well""",688,±487,"Malayalam, Kannada, or other Dravidian languages",0.01,3946.0,17.44
74,NaN,74664,±7547,"Chinese (incl. Mandarin, Cantonese)",1.26,74664.0,100.00
75,"Speak English ""very well""",39071,±4449,"Chinese (incl. Mandarin, Cantonese)",0.66,74664.0,52.33
76,"Speak English less than ""very well""",35593,±5192,"Chinese (incl. Mandarin, Cantonese)",0.60,74664.0,47.67
77,NaN,7103,±1667,Japanese,0.12,7103.0,100.00
78,"Speak English ""very well""",4102,±1155,Japanese,0.07,7103.0,57.75
79,"Speak English less than ""very well""",3001,±1079,Japanese,0.05,7103.0,42.25
80,NaN,35309,±4895,Korean,0.60,35309.0,100.00
81,"Speak English ""very well""",19433,±3205,Korean,0.33,35309.0,55.04
82,"Speak English less than ""very well""",15876,±2921,Korean,0.27,35309.0,44.96
83,NaN,194,±313,Hmong,0.00,194.0,100.00
84,"Speak English ""very well""",194,±313,Hmong,0.00,194.0,100.00
85,"Speak English less than ""very well""",0,±228,Hmong,0.00,194.0,0.00
86,NaN,20780,±3991,Vietnamese,0.35,20780.0,100.00
87,"Speak English ""very well""",10582,±2422,Vietnamese,0.18,20780.0,50.92
88,"Speak English less than ""very well""",10198,±2586,Vietnamese,0.17,20780.0,49.08
89,NaN,1802,±864,Khmer,0.03,1802.0,100.00
90,"Speak English ""very well""",772,±538,Khmer,0.01,1802.0,42.84
91,"Speak English less than ""very well""",1030,±570,Khmer,0.02,1802.0,57.16
92,NaN,3879,±1099,"Thai, Lao, or other Tai-Kadai languages",0.07,3879.0,100.00
93,"Speak English ""very well""",2424,±808,"Thai, Lao, or other Tai-Kadai languages",0.04,3879.0,62.49
94,"Speak English less than ""very well""",1455,±529,"Thai, Lao, or other Tai-Kadai languages",0.02,3879.0,37.51
95,NaN,12096,±3710,Other languages of Asia,0.20,12096.0,100.00
96,"Speak English ""very well""",7463,±2527,Other languages of Asia,0.13,12096.0,61.70
97,"Speak English less than ""very well""",4633,±1605,Other languages of Asia,0.08,12096.0,38.30
98,NaN,44915,±6885,Tagalog (incl. Filipino),0.76,44915.0,100.00
99,"Speak English ""very well""",31227,±5666,Tagalog (incl. Filipino),0.53,44915.0,69.52
100,"Speak English less than ""very well""",13688,±3173,Tagalog (incl. Filipino),0.23,44915.0,30.48
101,NaN,8585,±2359,"Ilocano, Samoan, Hawaiian, or other Austronesi...",0.15,8585.0,100.00
102,"Speak English ""very well""",5168,±1778,"Ilocano, Samoan, Hawaiian, or other Austronesi...",0.09,8585.0,60.20
103,"Speak English less than ""very well""",3417,±1258,"Ilocano, Samoan, Hawaiian, or other Austronesi...",0.06,8585.0,39.80
104,NaN,19491,±4360,Arabic,0.33,19491.0,100.00
105,"Speak English ""very well""",13673,±3606,Arabic,0.23,19491.0,70.15
106,"Speak English less than ""very well""",5818,±2023,Arabic,0.10,19491.0,29.85
107,NaN,6160,±1789,Hebrew,0.10,6160.0,100.00
108,"Speak English ""very well""",5830,±1795,Hebrew,0.10,6160.0,94.64
109,"Speak English less than ""very well""",330,±270,Hebrew,0.01,6160.0,5.36
110,NaN,44299,±6897,"Amharic, Somali, or other Afro-Asiatic languages",0.75,44299.0,100.00
111,"Speak English ""very well""",31339,±5848,"Amharic, Somali, or other Afro-Asiatic languages",0.53,44299.0,70.74
112,"Speak English less than ""very well""",12960,±2553,"Amharic, Somali, or other Afro-Asiatic languages",0.22,44299.0,29.26
113,NaN,75279,±9886,"Yoruba, Twi, Igbo, or other languages of Weste...",1.27,75279.0,100.00
114,"Speak English ""very well""",63495,±8676,"Yoruba, Twi, Igbo, or other languages of Weste...",1.07,75279.0,84.35
115,"Speak English less than ""very well""",11784,±3125,"Yoruba, Twi, Igbo, or other languages of Weste...",0.20,75279.0,15.65
116,NaN,13650,±4695,"Swahili or other languages of Central, Eastern...",0.23,13650.0,100.00
117,"Speak English ""very well""",10620,±3651,"Swahili or other languages of Central, Eastern...",0.18,13650.0,77.80
118,"Speak English less than ""very well""",3030,±1639,"Swahili or other languages of Central, Eastern...",0.05,13650.0,22.20
119,NaN,0,±228,Navajo,0.00,0.0,NaN
120,"Speak English ""very well""",0,±228,Navajo,0.00,0.0,NaN
121,"Speak English less than ""very well""",0,±228,Navajo,0.00,0.0,NaN
122,NaN,733,±640,Other Native languages of North America,0.01,733.0,100.00
123,"Speak English ""very well""",614,±561,Other Native languages of North America,0.01,733.0,83.77
124,"Speak English less than ""very well""",119,±194,Other Native languages of North America,0.00,733.0,16.23
125,NaN,17228,±4523,Other and unspecified languages,0.29,17228.0,100.00
126,"Speak English ""very well""",12110,±3383,Other and unspecified languages,0.20,17228.0,70.29
127,"Speak English less than ""very well""",5118,±2541,Other and unspecified languages,0.09,17228.0,29.71

In [28]:
stacked_specific_lang_proficiency_state_df = (lang_specific_proficiency_state_df.pivot_table(index='language',
                                                                                             columns='proficiency',
                                                                                             values='proficiency_pct_by_language',
                                                                                             aggfunc='sum').fillna(0).reset_index())

In [29]:
stacked_specific_lang_proficiency_state_df

speaker_totals = (lang_specific_proficiency_state_df[['language', 'speaker_count_by_language']].drop_duplicates())

stacked_specific_lang_proficiency_state_df = (stacked_specific_lang_proficiency_state_df
    .merge(speaker_totals, on='language', how='left')

In [31]:
stacked_specific_lang_proficiency_state_df['speaker_count_by_language']=stacked_specific_lang_proficiency_state_df['speaker_count_by_language'].astype(int)

In [35]:
stacked_specific_lang_proficiency_state_df=stacked_specific_lang_proficiency_state_df.drop('Speak only English', axis=1)

In [36]:
stacked_specific_lang_proficiency_state_df

,language,"Speak English ""very well""","Speak English less than ""very well""",speaker_count_by_language
0,"Amharic, Somali, or other Afro-Asiatic languages",71.0,29.0,44299
1,Arabic,70.0,30.0,19491
2,Armenian,76.0,24.0,2174
3,Bengali,67.0,33.0,16169
4,"Chinese (incl. Mandarin, Cantonese)",52.0,48.0,74664
5,English,0.0,0.0,4624493
6,French (incl. Cajun),74.0,26.0,59893
7,German,89.0,11.0,15592
8,Greek,82.0,18.0,6089
9,Gujarati,80.0,20.0,10369
10,Haitian,72.0,28.0,16844
11,Hebrew,95.0,5.0,6160
12,Hindi,82.0,18.0,22610
13,Hmong,100.0,0.0,194
14,"Ilocano, Samoan, Hawaiian, or other Austronesi...",60.0,40.0,8585
15,Italian,78.0,22.0,7754
16,Japanese,58.0,42.0,7103
17,Khmer,43.0,57.0,1802
18,Korean,55.0,45.0,35309
19,"Malayalam, Kannada, or other Dravidian languages",83.0,17.0,3946
20,Navajo,0.0,0.0,0
21,"Nepali, Marathi, or other Indic languages",75.0,25.0,12872
22,Other Indo-European languages,65.0,35.0,12707
23,Other Native languages of North America,84.0,16.0,733
24,Other and unspecified languages,70.0,30.0,17228
25,Other languages of Asia,62.0,38.0,12096
26,"Persian (incl. Farsi, Dari)",64.0,36.0,16666
27,Polish,72.0,28.0,3795
28,Portuguese,62.0,38.0,16069
29,Punjabi,79.0,21.0,5965
30,Russian,63.0,37.0,19214
31,Serbo-Croatian,51.0,49.0,2049
32,Spanish,53.0,47.0,597081
33,"Swahili or other languages of Central, Eastern...",78.0,22.0,13650
34,Tagalog (incl. Filipino),70.0,30.0,44915
35,Tamil,87.0,13.0,9049
36,Telugu,89.0,11.0,11834
37,"Thai, Lao, or other Tai-Kadai languages",62.0,38.0,3879
38,Ukrainian or other Slavic languages,72.0,28.0,8531
39,Urdu,62.0,38.0,19812
40,Vietnamese,51.0,49.0,20780
41,"Yiddish, Pennsylvania Dutch or other West Germ...",84.0,16.0,4503
42,"Yoruba, Twi, Igbo, or other languages of Weste...",84.0,16.0,75279

In [37]:
stacked_specific_lang_proficiency_state_df.to_csv("stacked_specific_lang_proficiency_state_df.csv")

In [42]:
#Number of residents who speak a language other than English at home 

stacked_specific_lang_proficiency_state_df.loc[stacked_specific_lang_proficiency_state_df['language'] != 'English', 'speaker_count_by_language'].sum()

np.int64(1287754)

In [44]:
#percentage of estimated pop that speak a language other than English in their homes 
(1287754/5912247)*100

21.78112653277172

In [43]:
#minimum number of different languages spoken 
stacked_specific_lang_proficiency_state_df['language'].count

<bound method Series.count of 0      Amharic, Somali, or other Afro-Asiatic languages
1                                                Arabic
2                                              Armenian
3                                               Bengali
4                   Chinese (incl. Mandarin, Cantonese)
5                                               English
6                                  French (incl. Cajun)
7                                                German
8                                                 Greek
9                                              Gujarati
10                                              Haitian
11                                               Hebrew
12                                                Hindi
13                                                Hmong
14    Ilocano, Samoan, Hawaiian, or other Austronesi...
15                                              Italian
16                                             Japanese
17                                                Khmer
18                                               Korean
19     Malayalam, Kannada, or other Dravidian languages
20                                               Navajo
21            Nepali, Marathi, or other Indic languages
22                        Other Indo-European languages
23              Other Native languages of North America
24                      Other and unspecified languages
25                              Other languages of Asia
26                          Persian (incl. Farsi, Dari)
27                                               Polish
28                                           Portuguese
29                                              Punjabi
30                                              Russian
31                                       Serbo-Croatian
32                                              Spanish
33    Swahili or other languages of Central, Eastern...
34                             Tagalog (incl. Filipino)
35                                                Tamil
36                                               Telugu
37              Thai, Lao, or other Tai-Kadai languages
38                  Ukrainian or other Slavic languages
39                                                 Urdu
40                                           Vietnamese
41    Yiddish, Pennsylvania Dutch or other West Germ...
42    Yoruba, Twi, Igbo, or other languages of Weste...
Name: language, dtype: str>